<?php $store = $this->getMyStoreInfo(Factory::getSession('customer/id'))?>
<?php if (!$store):?>
<script type="text/javascript">
window.location.href = '/customer/store/apply';
</script>
<?php endif?>
<div id="store-setting" class="store_apply_layout">
	<h1>店铺资料</h1>
	<table width="760" style="margin-top:12px;">
		<tbody>
			<tr>
				<th width="70">
					<label>店铺名称：</label>
				</th>
				<td><span><?php echo $store['name']?></span></td>
			</tr>
			<tr>
				<th>
					<label>营业执照：</label>
				</th>
				<td><img style="margin:5px;height:200px;" src="<?php echo $store['license']?>" /></td>
			</tr>
			<tr>
				<th>
					<label>店主姓名：</label>
				</th>
				<td><?php echo $store['username']?></td>
			</tr>
			<tr>
				<th>
					<label>手机号码：</label>
				</th>
				<td><?php echo $store['mobile']?></td>
			</tr>
			<tr>
				<th>
					<label>联系QQ：</label>
				</th>
				<td><?php echo $store['qq']?></td>
			</tr>
			<tr>
				<th>
					<label>店铺地址：</label>
				</th>
				<td>
					<?php foreach ($store['addr'] as $item):?>
					<span>[<?php echo $item['region']?>]<?php echo $item['addr']?>；</span>
					<?php endforeach?>
				</td>
			</tr>
			<tr>
				<th>
					<label>店铺介绍：</label>
				</th>
				<td>
					<div><?php echo $store['introduction']?></div>
				</td>
			</tr>
			<tr>
				<th>
					<label>店铺相片：</label>
				</th>
				<td>
					<div class="upload_img">
						<div id="store-thumbnails" style="margin-top:5px;">
							<?php foreach ($store['gallery'] as $item) :?>
							<div class="pack">
								<div class="pack-img">
								<img style="margin:5px;border:solid 1px #ddd;" src="/upload/store/<?php echo $item?>" />
								</div>
							</div>
							<?php endforeach?>
							<div class="clear"></div>
						</div>
					</div>
				</td>
			</tr>
		</tbody>
	</table>
</div>
