<?php $activity = $this->loadMyActivityList()?>
<?php $types = Factory::getView('activity/list')->getActivityType()?>
<div class="tabs1">
	<ul>
    	<li class="tabs1_c">
    		<a href="javascript:void(0);">店铺活动</a>
    	</li>
    	<li>
    		<a href="/customer/store/activity-apply?cfrom=uc_tab">活动申请</a>
    	</li>
    </ul>
</div>
<p class="red" style="text-align:center;margin:5px;">注：目前每间店铺只能同时申请一次活动机会！</p>
<div class="store_apply_layout">
	<table class="sales_blank" width="760">
		<thead style="background-color:#D4D4D4;">
			<tr>
				<th>活动类型</th>
				<th>活动标题</th>
				<th>状态</th>
				<th style="width:100px;">操作</th>
			</tr>
		</thead>
		<tbody>
			<?php if ($activity):?>
			<?php foreach ($activity as $item):?>
			<tr>
				<td><?php echo $types[$item['type']]?></td>
				<td><?php echo $item['title']?></td>
				<td class="status" active="<?php echo $item['status']?>"><?php echo $item['status'] == 1 ? '有效' : '已过期'?></td>
				<td>
					<?php if ($item['status'] == 1 || $item['status'] == -1):?>
					<a class="red" href="javascript:void(0);" onclick="setExpired(this, '<?php echo $item['id']?>');">过期</a>
					<?php endif?>
					<a href="javascript:void(0);" onclick="editActivity(this, '<?php echo $item['id']?>');">修改</a>
				</td>
			</tr>
			<?php endforeach?>
			<?php else:?>
			<tr>
				<td colspan="4">暂无相关活动记录，<a class="blue" href="/customer/store/activity-apply?cfrom=activity-list">立即参与</a></td>
			</tr>
			<?php endif?>
		</tbody>
	</table>
</div>
<script type="text/javascript">
//编辑活动
function editActivity(obj, id)
{
	if (jQuery(obj).parent().parent().find('.status').attr('active') == '0') {
		var num = 0;
		jQuery('.status').each(function(){
			if (jQuery(this).attr('active') == '1') {
				num++;
			}
		});
		if (num > 0) {
			alert('目前每间店铺只能同时申请一次活动机会，请先将其它有效活动置为过期，再对本信息进行编辑！');
			return;
		}
	}
	window.location.href = '/customer/store/activity-apply?id=' + id + '&cfrom=uc_activity_list';
}
//活动置为过期
function setExpired(obj, id)
{
	if (!confirm('确定将该活动置为过期？')) {
		return;
	}
	jQuery.ajax({
		type:'get',
		data:{id:id},
		dataType:'json',
		url:'/customer/store/set-activity-expired',
		beforeSend:function(){
			jQuery(obj).html('正在提交').attr('disabled', 'disabled');
		},
		success:function(data){
			if (data == '1') {
				jQuery(obj).parent().parent().find('td:eq(2)').html('已过期').attr('active', '0');
				jQuery(obj).remove();
			} else {
				alert('设置过期失败，请稍候尝试');
				jQuery(obj).html('过期').removeAttr('disabled');
			}
		},
		error:function(){
			alert('设置过期失败，请稍候尝试');
			jQuery(obj).html('过期').removeAttr('disabled');
		}
	});
}
</script>
