<?php $id = Factory::getRequest()->getParam('id')?>
<?php $tablet = $this->showInfo($id)?>
<title>【<?php echo $tablet['title']?>】-顺德二手平板-机荒网</title>
<meta name="KEYWORDS" content='顺德平板,顺德平板交易,顺德二手平板,<?php echo $tablet['data']['brand']?>,<?php echo $tablet['data']['model']?>,顺德闲置平板,佛山平板交易,佛山二手平板,机荒网' />
<meta name="DESCRIPTION" content='<?php echo $tablet['title']?>,<?php echo $tablet['data']['brand']?>,<?php echo $tablet['data']['model']?>' />
