<?php global $PStatic;?>
<?php $brands = Factory::getView('system/mlib')->loadBrandList()?>
<script type="text/javascript">
jQuery(document).ready(function(){
	jQuery('.info_type').click(function(){
		jQuery('input[name=info_type]:checked').removeAttr('checked');
		jQuery(this).find('input[name=info_type]').attr('checked', 'checked');
		switch (jQuery(this).find('input[name=info_type]').val()) {
			case '1':
				window.location.href = '/customer/mobile/publish?cfrom=publish';
				break;
			case '0':
				window.location.href = '/customer/purchase/publish?cfrom=publish';
				break;
		}
	});
});
</script>
<table id="base_info" class="post_table">
	<tbody>
    	<tr>
        	<th><span class="red">*</span> 信息类型</th>
            <td>
                <label class="info_type">
                    <input name="info_type" type="radio" value="1" />
                    <span>转让</span>
                </label>
            	<label class="info_type">
                	<input name="info_type" type="radio" value="0" checked="checked" />
                    <span>求购</span>
                </label>
            </td>
        </tr>
    	<tr>
        	<th><span class="red">*</span> 标题信息</th>
            <td>
            	<input name="title" class="purchase_title" type="text" onfocus="showMsg('pur_title', 'focus');" />
                <!--提示信息ks-->
                <div class="post_tis tis_pur_title">
                	<span class="focus">6-50个字，不能填写特殊字符</span>
                	<span class="empty">标题不能为空！</span>
                	<span class="error">标题不能少于6个字，多于50个字！</span>
                	<span class="right"></span>
                </div>
                <!--提示信息end-->
            </td>
        </tr>
    	<tr>
        	<th><span class="red">*</span> 手机品牌</th>
            <td>
            	<select name="brand" class="default_selt" onclick="checkTitle();">
                	<option value="">请选择</option>
					<?php foreach ($brands as $key => $value):?>
					<option value="<?php echo $key?>"><?php echo $value?></option>
					<?php endforeach?>
                </select>
                <!--提示信息ks-->
                <div class="post_tis tis_pur_brand">
                	<span class="empty">请选择品牌！</span>
                	<span class="right"></span>
                </div>
                <!--提示信息end-->
            </td>
        </tr>
    	<tr style="display:none;">
        	<th><span class="red">*</span> 手机型号</th>
            <td>
            	<select class="default_selt">
                	<option value="" selected="selected">--请选择--</option>
                	<option value="">--iphone4s--</option>
                </select>
                <!--提示信息ks-->
                <div class="post_tis tis_pur_xinghao">
                	<span class="empty">请选择型号！</span>
                	<span class="right"></span>
                </div>
                <!--提示信息end-->
            </td>
        </tr>
    	<tr>
        	<th><span class="red">* </span>价格范围</th>
            <td class="price_range">
            	<input name="min-price" maxlength="5" type="text" onfocus="checkBrand();" />
                <span> ~ </span>
                <input name="max-price" maxlength="5" type="text" onfocus="checkBrand();" />
                <span> 元</span>
                <!--交易价格提示信息ks-->
                <div class="post_tis tis_pur_price">
                	<span class="focus">只能填写整数，最低价不能大于最高价</span>
                	<span class="empty">交易价格不能为空！</span>
                	<span class="error">只能输入整数，最低价不能大于最高价！</span>
                	<span class="right"></span>
                </div>
                <!--交易价格提示信息end-->
            </td>
        </tr>
    	<tr>
        	<th><span class="red">* </span>求购数量</th>
            <td>
            	<input name="amount" class="purchase_num" type="text" value="1" onfocus="checkPrice();" />
                <span>/部</span>
                <!--求购数量提示信息ks-->
                <div class="post_tis tis_pur_num">
                	<span class="focus">只能填写数字</span>
                	<span class="error">请填写整数数字</span>
                	<span class="right"></span>
                </div>
                <!--求购数量提示信息end-->
            </td>
        </tr>
    	<tr>
        	<th><span class="red">* </span>备注信息</th>
            <td>
            	<textarea name="remark" class="supplement" onfocus="checkAmount();"></textarea>
                <!--提示信息ks-->
                <div class="post_tis tis_pur_miaoshu">
                	<span class="focus">10-500个字，不能填写特殊字符</span>
                	<span class="empty">手机描述不能为空！</span>
                	<span class="error">手机描述不能少于10个字，多于500个字！</span>
                	<span class="right"></span>
                </div>
                <!--提示信息end-->
            </td>
        </tr>
		<tr>
			<th style="padding-top:20px;"><span class="red">*</span> 关于有效期</th>
			<td>
				<p>
					亲爱的用户，您所发布的信息<span class="red" style="font-weight:bold;">每24小时只能刷新一次</span>，如果您所发布的信息在<span class="red" style="font-weight:bold;">30天内</span>都没有进行刷新操作，系统会自动对您的信息进行过期处理，届时其他用户将不会看到您所发布的信息，您的过期信息将保存在“我发布的求购”栏目的过期信息中！
				</p>
            </td>
		</tr>
    	<tr>
        	<th></th>
            <td>
            	<a class="btn_blue next_step_btn" href="javascript:void(0);" style="margin-top:0px;" onclick="checkRemark();">下一步，填写联系信息</a>
            </td>
        </tr>
	</tbody>
</table>
