<?php global $CStatic;?>
<table id="contact_info" class="post_table" style="display:none;">
	<tbody>
		<tr>
			<th><span class="red">*</span> 联 系 人</th>
			<td>
				<input name="name" type="text" onfocus="showMsg('lxr', 'focus')" />
                <!--提示信息ks-->
                <div class="post_tis tis_lxr">
                	<span class="focus">2-10个字，如"余先生"</span>
                	<span class="empty">联系人不能为空！</span>
                	<span class="error">联系人不能少于2个字，多于10个字！</span>
                	<span class="right"></span>
                </div>
                <!--提示信息end-->
			</td>
		</tr>
		<tr>
			<th><span class="red">*</span> 联系电话</th>
			<td>
				<input name="tel" type="text" onfocus="checkName();" />
                <!--提示信息ks-->
                <div class="post_tis tis_phone">
                	<span class="focus">请填写电话，如18011112222、672222</span>
                	<span class="empty">联系电话不能为空！</span>
                	<span class="right"></span>
                </div>
                <!--提示信息end-->
			</td>
		</tr>
		<tr>
			<th><span class="red">*</span> Q Q 号码</th>
			<td>
				<input name="qq" type="text" maxlength="13" onfocus="checkTel();" />
                <!--提示信息ks-->
                <div class="post_tis tis_qq">
                	<span class="focus">5-13个数字，填写QQ号更方便联系</span>
                	<span class="empty">QQ号不能为空！</span>
                	<span class="error">QQ号长度不能少于5或多于13！</span>
                	<span class="right"></span>
                </div>
                <!--提示信息end-->
			</td>
		</tr>
		<tr>
			<th><span class="red">*</span> 交易地区</th>
			<td>
            	<select name="region" class="default_selt" onclick="checkQQ();">
                	<option value="">请选择</option>
					<?php foreach ($CStatic['region'] as $key => $value):?>
					<option value="<?php echo $key?>"><?php echo $value?></option>
					<?php endforeach?>
                </select>
                <!--提示信息ks-->
                <div class="post_tis tis_area">
                	<span class="empty">请选择交易地区！</span>
                	<span class="right"></span>
                </div>
                <!--提示信息end-->
			</td>
		</tr>
		<tr>
			<th><span class="red">*</span> 交易地点</th>
			<td>
				<input name="location" type="text" style="width:400px;" onfocus="checkRegion();" />
                <!--提示信息ks-->
                <div class="post_tis tis_didian">
					<span class="focus">请填写交易地点，3-30个字</span> 
					<span class="empty">请输入交易地点</span>
					<span class="error">交易地点不能少于3个字，不能多于30个字</span>
                	<span class="right"></span>
                </div>
                <!--提示信息end-->
			</td>
		</tr>
		<tr>
			<th style="padding-top:20px;"><span class="red">*</span> 关于诚信交易</th>
			<td>
				<p class="red" style="font-weight:bold;">亲爱的用户，您所发布信息中的联系信息将会记录在机荒网内并形成用户交易名单，以用作交易诚信度监测，请诚信交易！</p>
            </td>
		</tr>
		<tr>
			<th></th>
			<td>
				<a class="next_step_btn btn_blue" href="javascript:void(0);" onclick="checkLocation(this);">确认发布</a>
			</td>
		</tr>
	</tbody>
</table>
