<?php $id = Factory::getRequest()->getParam('id')?>
<?php $summarize = $this->getSummarize($id)?>
<!--发布成功ks-->
<table id="publish_success" class="success_table">
	<tbody>
		<tr>
			<th width="100" class="tar">
				<div class="succes_icon"></div>
			</th>
			<td>
				<p style="font-size:28px; color:#000;">恭喜您，发布成功!</p>
			</td>
		</tr>
		<tr>
			<th class="fs14"></th>
			<td>
				<label style="font-size: 18px !important;vertical-align: top;">您现在可以：</label>
				<script type="text/javascript" charset="utf-8">
				(function(){
				  var _w = 106 , _h = 24;
				  var param = {
					url:base + '/purchase/item?id=<?php echo $id?>',
					type:'5',
					count:'', /**是否显示分享数，1显示(可选)*/
					appkey:'mobilefrom', /**您申请的应用appkey,显示分享来源(可选)*/
					title:'<?php echo $summarize['title']?>', /**分享的文字内容(可选，默认为所在页面的title)*/
					ralateUid:'2785673680', /**关联用户的UID，分享微博会@该用户(可选)*/
					language:'zh_cn', /**设置语言，zh_cn|zh_tw(可选)*/
					rnd:new Date().valueOf()
				  }
				  var temp = [];
				  for( var p in param ){
					temp.push(p + '=' + encodeURIComponent( param[p] || '' ) )
				  }
				  document.write('<iframe allowTransparency="true" frameborder="0" scrolling="no" src="http://hits.sinajs.cn/A1/weiboshare.html?' + temp.join('&') + '" width="'+ _w+'" height="'+_h+'"></iframe>')
				})()
				</script>
			</td>
		</tr>
		<tr>
			<th></th>
			<td class="other_cz">
				<a class="blue gotoedit" style="padding-left:0px;" href="/customer/purchase/publish?cfrom=publish&id=<?php echo $id?>">返回编辑</a>
				<a class="blue" href="/customer/purchase/publish?cfrom=publish">继续发布</a>
				<a class="blue gotolook" href="/purchase/item?cfrom=publish&id=<?php echo $id?>">查看发布结果</a>
			</td>
		</tr>
	</tbody>
</table>
<!--发布成功end-->
