<?php $id = Factory::getRequest()->getParam('id', null)?>
<?php $model = $this->getModelName($id)?>
<title><?php echo $model['model'] . '-' . $model['brand']?>最新报价-顺德平板导购-机荒网</title>
<meta name="KEYWORDS" content='<?php echo $model['model'] . ',' . $model['brand']?>,顺德平板导购,顺德平板,顺德平板交易,顺德二手平板,顺德闲置平板,佛山平板交易,佛山二手平板,机荒网' />
<meta name="DESCRIPTION" content='<?php echo $model['model'] . ',' . $model['brand']?>,顺德平板导购' />
