<div class="m_i_d_title">
	<span>主要参数：</span>
</div>
<table>
	<tr>
		<th>CPU型号</th>
		<td></td>
		<td>---</td>
	</tr>
	<tr>
		<th>CPU频率</th>
		<td></td>
		<td>---</td>
	</tr>
	<tr>
		<th>核心数</th>
		<td></td>
		<td id="percent_8">---</td>
	</tr>
	<tr>
		<th>RAM容量</th>
		<td></td>
		<td id="percent_9">---</td>
	</tr>
	<tr>
		<th>屏幕尺寸</th>
		<td></td>
		<td id="percent_2">---</td>
	</tr>
	<tr>
		<th>屏幕分辨率</th>
		<td></td>
		<td id="percent_1">---</td>
	</tr>
	<tr>
		<th>前置摄像头</th>
		<td></td>
		<td id="percent_3">---</td>
	</tr>
	<tr>
		<th>后置摄像头</th>
		<td></td>
		<td id="percent_4">---</td>
	</tr>
	<tr>
		<th>操作系统</th>
		<td></td>
		<td>---</td>
	</tr>
	<tr>
		<th>扩容类型</th>
		<td></td>
		<td>---</td>
	</tr>
</table>
<script type="text/javascript">
jQuery(document).ready(function(){
	jQuery('.tlib_item_data table tr:eq(0) td:eq(0)').html(jQuery('#cpu_type').html());
	jQuery('.tlib_item_data table tr:eq(1) td:eq(0)').html(jQuery('#cpu_frequency').html());
	jQuery('.tlib_item_data table tr:eq(2) td:eq(0)').html(jQuery('#core_number').html());
	jQuery('.tlib_item_data table tr:eq(3) td:eq(0)').html(jQuery('#ram').html());
	jQuery('.tlib_item_data table tr:eq(4) td:eq(0)').html(jQuery('#screen_size').html());
	jQuery('.tlib_item_data table tr:eq(5) td:eq(0)').html(jQuery('#screen_resolution').html());
	jQuery('.tlib_item_data table tr:eq(6) td:eq(0)').html(jQuery('#front_camera').html());
	jQuery('.tlib_item_data table tr:eq(7) td:eq(0)').html(jQuery('#back_camera').html());
	jQuery('.tlib_item_data table tr:eq(8) td:eq(0)').html(jQuery('#os').html());
	jQuery('.tlib_item_data table tr:eq(9) td:eq(0)').html(jQuery('#expansion').html());
});
</script>
