<?php $id = Factory::getRequest()->getParam('store', null)?>
<?php $info = $this->getStorePublicInfo($id)?>
<!--店铺logo ks-->
<div class="store_info sidebar_item">
	<div class="store_logo">
		<img src="http://mobilefrom-upload.stor.sinaapp.com/thumbnail/<?php echo $info['customer_id']?>.jpg" onerror="loadErrorStoreThumbnail(this);"/>
    </div>
    <p>
		<span class="l">商品数：<?php echo $info['total']?></span>
        <span class="r">访问数量：<?php echo $info['clicks']?></span>
        <div class="clear"></div>
    </p>
	<?php if ($this->isMyStore($id, Factory::getSession('customer/id'))):?>
    <button type="button" onclick="window.location.href='/customer';">管理店铺</button>
	<?php endif?>
</div>
<!--店铺logo end-->
<!--在线客服ks-->
<div class="sidebar_item">
	<?php if ($info['notice']):?>
	<h3>店铺公告</h3>
    <div class="notice grey1">
		<p style="text-indent:2em;"><?php echo $info['notice']?></p>
    </div>
	<?php endif?>
	<?php if ($info['qq']):?>
	<h3 style="margin-top:10px;">在线客服</h3>
    <div class="im_qq_list">
		<?php foreach ($info['qq'] as $qq):?>
		<a target="_blank" rel="nofollow" href="/default/analysis/qq?uin=<?php echo $qq['num']?>&detail=store&store=<?php echo $store?>"><?php echo $qq['name'] . '：' . $qq['num']?></a>
		<?php endforeach?>
	</div>
	<?php endif?>
	<?php if ($info['tel']):?>
	<h3 style="margin-top:10px;">客服电话</h3>
	<div class="contact grey1">
		<?php foreach ($info['tel'] as $tel):?>
		<p><?php echo $tel['name'] . '：' . $tel['num']?></p>
		<?php endforeach?>
	</div>
	<?php endif?>
	<?php if ($info['working']):?>
	<h3 style="margin-top:10px;">工作时间</h3>
    <div class="work_time grey1">
		<?php foreach ($info['working'] as $value):?>
		<p><?php echo $value?></p>
		<?php endforeach?>
    </div>
	<?php endif?>
</div>
<!--在线客服end-->
<div class="store_search" style="display:none;">
	<input type="text" placeholder="店内搜索" />
    <input type="button" />
    <div class="clear"></div>
</div>
