<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xmlns:wb="http://open.weibo.com/wb">
<head>
	<?php echo $this->getChildHtml('skin')?>
</head>
<body>
	<div class="header">
		<?php echo $this->getChildHtml('header')?>
	</div>
    <div class="main">
    	<?php echo $this->getChildHtml('content')?>
    </div>
    <div class="footer">
    	<?php echo $this->getChildHtml('footer')?>
    </div>
    <div class="pop_window">
    	<?php echo $this->getChildHtml('pop_login')?>
    </div>
</body>
</html>