<?php $store_id = Factory::getView('customer/store')->getStoreId(Factory::getSession('customer/id'))?>
<?php $models = $this->loadMyMobileModelList($store_id)?>
<div class="tabs1">
	<ul>
    	<li class="tabs1_c">
    		<a href="javascript:void(0);">店铺手机</a>
    	</li>
    	<li>
    		<a href="/customer/store/tablet-list?cfrom=uc_tab">店铺平板</a>
		</li>
    </ul>
</div>
<div id="mobile-list" class="store_apply_layout">
	<?php if ($models):?>
	<div style="margin:10px 0;">
		<span style="font-weight:bold;">品牌筛选：</span>
		<select name="brand" style="width:auto;height:auto;">
			<option value="">选择品牌</option>
			<?php foreach ($models as $bid => $brand):?>
			<option value="<?php echo $bid?>"><?php echo $brand['label']?></option>
			<?php endforeach?>
		</select>
	</div>
	<?php endif?>
	<table class="sales_blank" width="760">
		<thead>
			<tr>
				<th>版本</th>
				<th>颜色</th>
				<th>容量(/G)</th>
				<th>新旧</th>
				<th>备注</th>
				<th style="width:70px;">价格(/元)</th>
				<th style="width:100px;">操作</th>
			</tr>
		</thead>
		<?php if ($models):?>
		<?php foreach ($models as $bid => $brand):?>
		<thead>
			<tr class="sales_brand_label">
				<th colspan="7"><?php echo $brand['label']?></th>
			</tr>
		</thead>
		<tbody brand="<?php echo $bid?>">
			<?php foreach ($brand['model'] as $mid => $model):?>
			<tr class="sales_model_label <?php echo $model['status'] == '2' ? 'inactive' : ''?>">
				<th style="width:380px;" colspan="4"><?php echo $model['label']?></th>
				<td style="width:360px;" colspan="3">
					<a class="blue" href="/customer/store/mobile-publish?id=<?php echo $mid?>">编辑</a>
					<?php if ($model['status'] == '1'):?>
						<a class="blue" href="javascript:void(0);" onclick="changeMobileModelStatus(this, '<?php echo $mid?>', '2');">下架</a>
						<?php if ($model['recommend'] == '1'):?>
						<a class="blue recommend" href="javascript:void(0);" v="0" onclick="changeMobileModelRecommend(this, '<?php echo $mid?>');">取消推荐</a>
						<?php else:?>
						<a class="blue recommend" href="javascript:void(0);" v="1" onclick="changeMobileModelRecommend(this, '<?php echo $mid?>');">推荐</a>
						<?php endif?>
						<?php if ($model['hot'] == '1'):?>
						<a class="blue" href="javascript:void(0);" v="0" onclick="changeMobileModelHot(this, '<?php echo $mid?>');">取消热销</a>
						<?php else:?>
						<a class="blue" href="javascript:void(0);" v="1" onclick="changeMobileModelHot(this, '<?php echo $mid?>');">热销</a>
						<?php endif?>
					<?php else:?>
					<a class="blue" href="javascript:void(0);" onclick="changeMobileModelStatus(this, '<?php echo $mid?>', '1');">上架</a>
					<?php endif?>
					<a class="red" href="javascript:void(0);" onclick="changeMobileModelStatus(this, '<?php echo $mid?>', '0');">删除</a>
				</td>
			</tr>
			<?php foreach ($model['mobile'] as $mobile):?>
			<tr class="sales_model_<?php echo $mid?> <?php echo $model['status'] == '2' || $mobile['status'] == '2' ? 'inactive' : ''?>" status="<?php echo $mobile['status']?>">
				<td v="<?php echo $mobile['version']?>"><?php echo $mobile['version']?></td>
				<td v="<?php echo $mobile['color']?>"><?php echo $mobile['color']?></td>
				<td v="<?php echo $mobile['storage']?>"><?php echo $mobile['storage']?></td>
				<td isnew="<?php echo $mobile['isnew']?>" v="<?php echo $mobile['newly']?>"><?php echo $mobile['newly']?></td>
				<td v="<?php echo $mobile['remark']?>"><?php echo $mobile['remark'] ? $mobile['remark'] : '---'?></td>
				<td v="<?php echo $mobile['price']?>"><?php echo $mobile['price']?></td>
				<td status="<?php echo $mobile['status']?>">
					<a class="blue" href="javascript:void(0);" onclick="editMobileItem(this, '<?php echo $mobile['store_mobile_id']?>');">编辑</a>
					<?php if ($mobile['status'] == '1'):?>
					<a class="blue" href="javascript:void(0);" onclick="changeMobileItemStatus(this, '<?php echo $mobile['store_mobile_id']?>', '2');">下架</a>
					<?php else:?>
					<a class="blue" href="javascript:void(0);" onclick="changeMobileItemStatus(this, '<?php echo $mobile['store_mobile_id']?>', '1');">上架</a>
					<?php endif?>
					<a class="red" href="javascript:void(0);" onclick="changeMobileItemStatus(this, '<?php echo $mobile['store_mobile_id']?>', '0');">删除</a>
				</td>
			</tr>
			<?php endforeach?>
			<?php endforeach?>
		</tbody>
		<?php endforeach?>
		<?php else:?>
		<tbody>
			<tr>
				<td colspan="7">暂无相关手机信息发布记录，<a class="blue" href="/customer/store/mobile-publish?cfrom=mobile-list">立即发布</a></td>
			</tr>
		</tbody>
		<?php endif?>
	</table>
</div>
<script type="text/javascript">
jQuery(document).ready(function(){
	jQuery('.sales_brand_label th').click(function(){
		var index = jQuery('table thead').index(jQuery(this).parent().parent());
		if (jQuery('tbody:eq(' + (index - 1) + ')').css('display') == 'none') {
			if(!-[1,]){
				jQuery('tbody:eq(' + (index - 1) + ')').slideDown();
			}else{
				jQuery('tbody:eq(' + (index - 1) + ')').fadeIn();
			}
		} else {
			if(!-[1,]){
				jQuery('tbody:eq(' + (index - 1) + ')').slideUp();
			}else{
				jQuery('tbody:eq(' + (index - 1) + ')').fadeOut();
			}
		}
	});
	jQuery('.sales_blank tbody tr').mouseover(function(){
		if (!jQuery(this).hasClass('sales_model_label')) {
			jQuery(this).css('background-color', '#FAFAFA');
		}
	});
	jQuery('.sales_blank tbody tr').mouseout(function(){
		if (!jQuery(this).hasClass('sales_model_label')) {
			jQuery(this).css('background-color', '');
		}
	});
	jQuery('select[name=brand]').change(function(){
		var brand = jQuery(this).val();
		if (brand != '') {
			jQuery('.sales_blank tbody').hide();
			jQuery('.sales_blank tbody').each(function(){
				if (jQuery(this).attr('brand') == brand) {
					jQuery(this).show();
				}
			});
		} else {
			jQuery('.sales_blank tbody').show();
		}
	});
});
</script>
