<?php $brands = Factory::getView('system/mlib')->loadBrandList()?>
<?php unset($brands['15'])?>
<div class="tabs1">
	<ul>
    	<li class="tabs1_c">
    		<a href="javascript:void(0);">发布手机</a>
    	</li>
    	<li>
    		<a href="/customer/store/tablet-publish?cfrom=uc_tab">发布平板</a>
		</li>
    </ul>
</div>
<div id="mobile-publish" class="store_apply_layout">
	<table>
		<tbody>
			<tr>
				<td colspan="2" style="padding-bottom:0;">
					<span class="red">
					* 如果品牌库或型号库没有您所出售的品牌或型号信息，
					<a class="blue" href="http://wpa.qq.com/msgrd?v=3&uin=2824673297&site=www.mobilefrom.com&menu=yes">请联系我们！</a>
					</span>
				</td>
			</tr>
			<tr>
				<th>
					<span class="red">*</span>
					<label>选择品牌：</label>
				</th>
				<td>
					<select name="brand_id" onchange="selectMobileBrand(this);">
						<option value="">请选择手机品牌</option>
						<?php foreach ($brands as $key => $value):?>
						<option value="<?php echo $key?>"><?php echo $value?></option>
						<?php endforeach?>
					</select>
				</td>
			</tr>
			<tr>
				<th>
					<span class="red">*</span>
					<label>选择型号：</label>
				</th>
				<td>
					<select name="model_id" onchange="checkMobileModelExist();">
						<option value="">请选择手机型号</option>
					</select>
				</td>
			</tr>
		</tbody>
		<tbody>
			<tr>
				<th>
					<span class="red">*</span>
					<label>出售信息：</label>
				</th>
				<td>
					<table class="sales-field">
						<thead>
							<tr>
								<th style="width:100px;">版本</th>
								<th>颜色</th>
								<th>容量(/G)</th>
								<th>新旧</th>
								<th style="width:260px;">备注</th>
								<th>价格(/元)</th>
								<th>操作</th>
							</tr>
						</thead>
						<tbody>
							<tr class="new-field">
								<td><textarea class="vversion" style="width:100px;" onpropertychange="this.style.height=this.scrollHeight + 'px'" oninput="this.style.height=this.scrollHeight + 'px'" onfocus="getFocus(this);"></textarea></td>
								<td><textarea class="vcolor" onpropertychange="this.style.height=this.scrollHeight + 'px'" oninput="this.style.height=this.scrollHeight + 'px'" onfocus="getFocus(this);"></textarea></td>
								<td><textarea class="vstorage" onpropertychange="this.style.height=this.scrollHeight + 'px'" oninput="this.style.height=this.scrollHeight + 'px'" onfocus="getFocus(this);"></textarea></td>
								<td>
									<select class="visnew" style="width:60px;" onchange="setNewly(this);">
										<option value="1">全新</option>
										<option value="0">二手</option>
									</select>
									<textarea class="vnewly" style="display:none;" onpropertychange="this.style.height=this.scrollHeight + \'px\'" oninput="this.style.height=this.scrollHeight + \'px\'" onfocus="getFocus(this);">全新</textarea>
								</td>
								<td><textarea class="vremark" style="width:260px;" onpropertychange="this.style.height=this.scrollHeight + 'px'" oninput="this.style.height=this.scrollHeight + 'px'" onfocus="getFocus(this);"></textarea></td>
								<td><textarea class="vprice" onpropertychange="this.style.height=this.scrollHeight + 'px'" oninput="this.style.height=this.scrollHeight + 'px'" onfocus="getFocus(this);"></textarea></td>
								<td><a href="javascript:void(0);" onclick="removeSalesItem(this);">删除</a></td>
							</tr>
							<tr>
								<td colspan="7" style="width:670px;">
									<a class="blue" href="javascript:void(0);" onclick="addMoreSales(this);">+加一个</a>
								</td>
							</tr>
						</tbody>
					</table>
				</td>
			</tr>
			<tr>
				<th>
					<label>详情描述：</label>
				</th>
				<td>
					<div class="rstyle">
						<ul>
							<li>
								<a href="javascript:void(0);">字体</a>
								<ul class="roption">
									<li><a href="javascript:void(0);" onclick="execCommandOnElement(this, 'bold');">粗体</a></li>
									<li><a href="javascript:void(0);" onclick="execCommandOnElement(this, 'italic');">斜体</a></li>
									<li><a href="javascript:void(0);" onclick="execCommandOnElement(this, 'underline');">下划线</a></li>
								</ul>
							</li>
							<li>
								<a href="javascript:void(0);">排版</a>
								<ul class="roption">
									<li><a href="javascript:void(0);" onclick="execCommandOnElement(this, 'justifyCenter');">居中</a></li>
									<li><a href="javascript:void(0);" onclick="execCommandOnElement(this, 'justifyLeft');">左对齐</a></li>
									<li><a href="javascript:void(0);" onclick="execCommandOnElement(this, 'justifyRight');">右对齐</a></li>
								</ul>
							</li>
							<li>
								<a href="javascript:void(0);">颜色</a>
								<ul class="roption">
									<li><a href="javascript:void(0);" onclick="execCommandOnElement(this, 'foreColor', '#333');" style="color:#333;">黑色</a></li>
									<li><a href="javascript:void(0);" onclick="execCommandOnElement(this, 'foreColor', '#FF0000');" style="color:#FF0000;">红色</a></li>
									<li><a href="javascript:void(0);" onclick="execCommandOnElement(this, 'foreColor', '#0D61A8');" style="color:#0D61A8;">蓝色</a></li>
									<li><a href="javascript:void(0);" onclick="execCommandOnElement(this, 'foreColor', '#FCAE28');" style="color:#FCAE28;">黄色</a></li>
								</ul>
							</li>
						</ul>
						<div class="clear"></div>
					</div>
					<div id="remark" contenteditable="true"></div>
				</td>
			</tr>
			<tr>
				<th>
					<label>相关图片：</label>
				</th>
				<td>
					<input type="hidden" name="gallery" value="" />
					<script type="text/javascript" src="<?php echo $this->getPlugin('swfupload/js/swfupload.js')?>"></script>
					<script type="text/javascript" src="<?php echo $this->getPlugin('swfupload/js/store.js')?>"></script>
					<script type="text/javascript">
						var storeswfu;
						window.onload = function () {
							storeswfu = new SWFUpload({
								upload_url: "<?php echo $this->getStoreUploadUrl()?>",
								post_params: {"PHPSESSID": "<?php echo session_id()?>", "id": "<?php echo Factory::getSession('customer/id')?>"},
								file_size_limit : "5MB",	// 2MB
								file_types : "*.jpg;*.png;*.gif",
								file_types_description : "JPG/PNG/GIF Images",
								file_upload_limit : "10",
								file_queue_error_handler : fileQueueError,
								file_dialog_complete_handler : fileDialogComplete,
								upload_progress_handler : uploadStoreProgress,
								upload_error_handler : uploadError,
								upload_success_handler : uploadStoreSuccess,
								upload_complete_handler : uploadComplete,
								button_image_url : "",
								button_placeholder_id : "storeHolder",
								button_width: 67,
								button_height: 26,
								button_text : '<div class="button"></div>',
								button_text_style : '.button {font-size: 12px;}',
								button_text_top_padding: 0,
								button_text_left_padding: 0,
								button_window_mode: SWFUpload.WINDOW_MODE.TRANSPARENT,
								button_cursor: SWFUpload.CURSOR.HAND,
								flash_url : "<?php echo Factory::getBaseUrl()?>/plugin/swfupload/js/swfupload.swf",
								custom_settings : {
									upload_target : "upload-process"
								},
								debug: false
							});
						};
					</script>
					<div class="upload_img">
						<form>
							<div class="upload_img_btn">
								<div id="storeHolder"></div>
							</div>
							<div style="float:left; line-height:30px; margin-left:10px;">每张图片大小不能大于5M，且数量不能多于10张</div>
							<div class="clear"></div>
							<div class="red" style="line-height:30px;">注：点击拖动图片可调节图片顺序</div>
						</form>
						<div id="upload-process"></div>
					</div>
					<div class="upload_img">
						<div id="store-thumbnails" style="margin-top:5px;">
							<div class="clear"></div>
						</div>
					</div>
				</td>
			</tr>
			<tr>
				<td class="mbutton" colspan="2">
					<button class="mpublish" type="button" onclick="submitMobileModel(this);">发布</button>
					<button class="mcancle" type="button" onclick="window.location.href='/customer/store/mobile-list?cfrom=publish'">取消</button>
				</td>
			</tr>
		</tbody>
	</table>
</div>
<script type="text/javascript">
jQuery(document).ready(function(){
	//去除粘帖内容中的所有标签
	jQuery('#remark').bind('paste', function(){
		var e = jQuery(this);
		setTimeout(function() {
			var content = jQuery(e).html();
			var re=/<[^img][^>]+>/g;
			content = content.replace(re,"");
			jQuery(e).html(content);
		}, 100);
	});
});
<?php $id = Factory::getRequest()->getParam('id', null)?>
<?php if ($id):?>
getMobileModelInfo('<?php echo $id?>', 'edit');
<?php endif?>
</script>
