<script type="text/javascript">
jQuery(document).ready(function(){
	jQuery('.service_tabs li').mouseover(function(){
		jQuery('.service_tabs .selected').removeClass('selected');
		jQuery(this).addClass('selected');	
		var index = jQuery('.service_tabs li').index(jQuery(this));
		jQuery('.service_tabs_item').hide();
		jQuery('.service_tabs_item:eq(' + index + ')').show();
	});
	jQuery('.service_box').mouseover(function(){
		jQuery(this).css('background-color', 'whitesmoke');
	});
	jQuery('.service_box').mouseout(function(){
		jQuery(this).css('background-color', '');
	});
	jQuery('.service_box').click(function(){
		jQuery.ajax({
			type:'get',
			data:{sid:jQuery(this).attr('sid'), uid:jQuery(this).attr('uid')},
			dataType:'json',
			url:'/website/service/get-detail',
			success:function(data){
				if (data != '0') {
					var pop = jQuery('.service_pop');
					pop.find('.l img').attr('src', '/upload/thumbnail/' + data.customer_id + '.jpg');
					pop.find('.expert_name strong').html(data.contact.name);
					pop.find('.expert_phone strong').html(data.contact.tel);
					pop.find('.expert_qq a').attr('href', 'http://wpa.qq.com/msgrd?v=3&uin=' + data.contact.qq + '&site=www.mobilefrom.com&menu=yes');
					pop.find('.expert_area span:eq(1)').html(data.contact.region);
					pop.find('.expert_address span:eq(1)').html(data.contact.location);
					pop.find('.expert_charge .r').html(data.introduction);
					pop.show();
				} else {
					alert('获取服务信息失败，请稍候尝试');
				}
			},
			error:function(){
				alert('获取服务信息失败，请稍候尝试');
			}
		});
	});
	jQuery('.expert_pop .close').click(function(){
		jQuery('.service_pop').hide();
	});
	//获取浏览历史
	loadHistoryMobile();
	jQuery('.service_pop').css('width', window.screen.width)
						.css('height', window.screen.height);
});
</script>
<!--手机服务ks-->
<?php $id = Factory::getRequest()->getParam('id')?>
<?php $info = $this->showContact($id)?>
<?php global $CStatic?>
<?php $services = Factory::getView('customer/info')->loadRegionService($info['contact']['region'])?>
<?php if ($services):?>
<div class="mb_service" style="display:block;">
	<div class="hd">
		<h3>【<span class="red"><?php echo $CStatic['region'][$info['contact']['region']]?></span>】当地手机服务</h3>
    </div>
    <div class="bd">
    	<ul class="service_tabs">
        	<li class="selected"><a href="javascript:void(0);">验机</a></li>
        	<li><a href="javascript:void(0);">解锁</a></li>
        	<li><a href="javascript:void(0);">刷机</a></li>
        </ul>
		<div class="clear"></div>
        <div class="service_tabs_bd">
        	<!--验机服务ks-->
        	<div class="service_tabs_item">
				<?php if ($services['2']):?>
				<?php foreach ($services['2'] as $item):?>
				<div class="service_box" sid="<?php echo $item['sid']?>" uid="<?php echo $item['customer_id']?>">
                    <div class="l">
						<a>
							<img src="/upload/thumbnail/<?php echo $item['customer_id']?>.jpg" onerror="loadErrorStoreThumbnail(this);" />
						</a>
                    </div>
                    <div class="r">
						<p>
							<a class="blue"><?php echo $item['username']?></a>
						</p>
                        <p>
							<span>收费：<strong class="red">￥<?php echo $item['price']?></strong></span>
                        </p>
                    </div>
                    <div class="clear"></div>
                </div>
				<?php endforeach?>
				<?php else:?>
				<p style="text-align:center;padding-top:10px;">暂无相关信息</p>
				<?php endif?>
            </div>
        	<!--验机服务end-->
        	<!--解锁服务ks-->
        	<div class="service_tabs_item" style="display:none;">
				<?php if ($services['1']):?>
				<?php foreach ($services['1'] as $item):?>
                <div class="service_box" sid="<?php echo $item['sid']?>" uid="<?php echo $item['customer_id']?>">
                    <div class="l">
						<a>
							<img src="/upload/thumbnail/<?php echo $item['customer_id']?>.jpg" onerror="loadErrorStoreThumbnail(this);" />
						</a>
                    </div>
                    <div class="r">
						<p>
							<a class="blue"><?php echo $item['username']?></a>
						</p>
                        <p>
							<span>收费：<strong class="red">￥<?php echo $item['price']?></strong></span>
                        </p>
                    </div>
                    <div class="clear"></div>
                </div>
				<?php endforeach?>
				<?php else:?>
				<p style="text-align:center;padding-top:10px;">暂无相关信息</p>
				<?php endif?>
            </div>
        	<!--解锁服务end-->
        	<!--刷机服务ks-->
        	<div class="service_tabs_item" style="display:none;">
				<?php if ($services['3']):?>
				<?php foreach ($services['3'] as $item):?>
                <div class="service_box" sid="<?php echo $item['sid']?>" uid="<?php echo $item['customer_id']?>">
                    <div class="l">
						<a>
							<img src="/upload/thumbnail/<?php echo $item['customer_id']?>.jpg" onerror="loadErrorStoreThumbnail(this);" />
						</a>
                    </div>
                    <div class="r">
						<p>
							<a class="blue"><?php echo $item['username']?></a>
						</p>
                        <p>
							<span>收费：<strong class="red">￥<?php echo $item['price']?></strong></span>
                        </p>
                    </div>
                    <div class="clear"></div>
                </div>
				<?php endforeach?>
				<?php else:?>
				<p style="text-align:center;padding-top:10px;">暂无相关信息</p>
				<?php endif?>
            </div>
        	<!--刷机服务end-->
        </div>
    </div>
	<div class="service_pop">
		<div class="expert_pop">
			<a class="close" href="javascript:void(0);"></a>
			<div class="top">
				<div class="l">
					<img src="" onerror="loadErrorStoreThumbnail(this);" />
				</div>
				<div class="r">
					<div class="expert_name">
						<strong></strong>
						<a href="http://wpa.qq.com/msgrd?v=3&uin=2824673297&site=www.mobilefrom.com&menu=yes">[ 举报此人 ]</a>
					</div>
					<div class="expert_phone"><span class="grey1">手机：</span><strong class="red"></strong></div>
					<div class="expert_qq">
						<span class="grey1">交谈：</span>
						<a href="">
							<img src="http://pub.idqqimg.com/wpa/images/counseling_style_52.png" />
						</a>
						<div class="clear"></div>
					</div>
				</div>
				<div class="clear"></div>
			</div>
			<div class="middle">
				<div class="expert_area"><span class="grey1">所在地区：</span><span></span></div>
				<div class="expert_address">
                	<span class="l grey1">详细地址：</span>
                    <span class="r"></span>
                    <div class="clear"></div>
                </div>
				<div class="expert_charge">
					<div class="l"><span class="grey1">服务介绍：</span></div>
					<div class="r"></div>
					<div class="clear"></div>
				</div>
			</div>
			<div class="bottom">
				<p>O(∩_∩)O~我是商家，我可以<a class="blue" href="http://wpa.qq.com/msgrd?v=3&uin=2824673297&site=www.mobilefrom.com&menu=yes">提供本地手机服务>></a></p>
			</div>
		</div>
	</div>
</div>
<?php endif?>
<!--手机服务end-->
<?php if ($top = Factory::getView('mobile/list')->loadTopBrandList(5)):?>
<?php $brands = Factory::getView('system/mlib')->loadBrandList()?>
<!--其它热门品牌ks-->
<div class="hot_brand">
	<h3>热门品牌<span class="grey1"> / Hot Brand</span></h3>
	<?php foreach ($top as $item):?>
	<div class="brand_item">
		<a href="/mobile/list?cfrom=brand&filter[2]=<?php echo $item['value_id']?>"><?php echo $brands[$item['value_id']]?></a>
		<span>共<i class="red"><?php echo $item['amount']?></i>条转让</span>
		<div class="clear"></div>
	</div>
	<?php endforeach?>
</div>
<!--其它热门品牌end-->
<?php endif?>

<!--浏览记录ks-->
<div id="history" class="history" style="display:none;">
	<div class="title">
		<h3>您浏览过的手机</h3>
		<a class="blue" href="javascript:void(0);" onclick="clearHistoryMobile();">清空</a>
		<div class="clear"></div>
	</div>
	<div class="bd">
		<ul class="list"></ul>
	</div>
</div>
<!--浏览记录end-->
