<table class="table2">
	<tbody>
		<tr>
			<th width="85">填写密码：</th>
			<td>
				<input type="password" name="newpwd" />
			</td>
		</tr>
		<tr>
			<th>确认密码：</th>
			<td>
				<input type="password" name="repwd" />
			</td>
		</tr>
		<tr>
			<th></th>
			<td>
				<button type="button" class="btn_red" 
				onclick="resetPwd('<?php echo Factory::getRequest()->getParam('id')?>');">保存</button>
			</td>
		</tr>
	</tbody>
</table>
<script type="text/javascript">
function resetPwd(id)
{
	var newpwd = jQuery('input[name=newpwd]').val();
	var repwd = jQuery('input[name=repwd]').val();
	if(newpwd == '' || repwd == ''){
		alert('请填写密码及确认密码');
		return;
	}
	if(newpwd != repwd){
		alert('请确保两次输入密码一致');
		return;
	}
	jQuery.ajax({
		type:'get',
		data:{id:id, newpwd:newpwd},
		dataType:'json',
		url:'/monitor/customer_common/reset-pwd',
		success:function(data){
			if(data == '1'){
				jQuery('input[name=newpwd]').val('');
				jQuery('input[name=repwd]').val('');
				alert('密码修改成功');
			}else{
				alert('密码修改失败，请稍候尝试');
			}
		},
		error:function(){
			alert('密码修改失败，请稍候尝试');
		}
	});
}
</script>