<div class="contactus">
	<h1>联系我们</h1>
    <div class="contact_email">
    	<p style="left:130px; top:18px;">
    		网站咨询(QQ):&nbsp;&nbsp;&nbsp;2824673297
    	</p>
        <p style="left:130px; top:88px;">
        	客服邮箱:&nbsp;&nbsp;&nbsp;service@mobilefrom.com
        </p>
    </div>
    <div class="contact_method" style="display: none;">
    	<div class="contact_method_l">
        	<p>地址：<span class="grey">广州市天河区天河东路242号</span></p>
            <p style="margin-top:20px;">邮编：<span class="grey">510630</span></p>
            <p style="margin-top:20px;">Q 群：<span class="grey">120311051</span></p>
        </div>
    	<div class="contact_method_r">
        	<p><strong>关注我们</strong></p>
            <div class="guanzhu"></div>
        </div>
        <div class="clear"></div>
    </div>
</div>