<div class="survey">
	<div class="survey_title" style="border-bottom-color:#ccc;"><h1>机荒网改版<span class="blue">问卷调研</span></h1></div>
    <form method="post" action="#">
    <div class="survey_item">
        <h2>1.您在访问机荒网首页的过程中，总体满意度如何？（单选）</h2>
        <ul>
        	<li>
                <label>
                    <input name="manyi" value="" type="radio" />
                    <span>非常满意</span>
                </label>
            </li>
        	<li>
                <label>
                    <input name="manyi" value="" type="radio" />
                    <span>比较满意</span>
                </label>
            </li>
        	<li>
                <label>
                    <input name="manyi" value="" type="radio" />
                    <span>一般</span>
                </label>
            </li>
        	<li>
                <label>
                    <input name="manyi" value="" type="radio" />
                    <span>不太满意</span>
                </label>
            </li>
        	<li>
                <label>
                    <input name="manyi" value="" type="radio" />
                    <span>很不满意</span>
                </label>
            </li>
        </ul>
    </div>
    <div class="survey_item">
        <h2>2.您浏览首页过程中，关注或使用了哪些信息/功能？（多选）</h2>
        <ul>
        	<li>
                <label>
                    <input value="" type="checkbox" />
                    <span>广告图</span>
                </label>
            </li>
        	<li>
                <label>
                    <input value="" type="checkbox" />
                    <span>热门品牌</span>
                </label>
            </li>
        	<li>
                <label>
                    <input value="" type="checkbox" />
                    <span>闲置手机</span>
                </label>
            </li>
        	<li>
                <label>
                    <input value="" type="checkbox" />
                    <span>求购信息</span>
                </label>
            </li>
        	<li>
                <label>
                    <input value="" type="checkbox" />
                    <span>机荒微博</span>
                </label>
            </li>
        	<li>
                <label>
                    <input value="" type="checkbox" />
                    <span>其他信息</span>
                </label>
            </li>
        </ul>
    </div>
    <div class="survey_item">
        <h2>3.您能否在手机天地方便地找到想要的手机信息？（单选）</h2>
        <ul>
        	<li>
                <label>
                    <input name="find_info" value="" type="radio" />
                    <span>非常方便</span>
                </label>
            </li>
        	<li>
                <label>
                    <input name="find_info" value="" type="radio" />
                    <span>比较方便</span>
                </label>
            </li>
        	<li>
                <label>
                    <input name="find_info" value="" type="radio" />
                    <span>不太方便</span>
                </label>
            </li>
        	<li>
                <label>
                    <input name="find_info" value="" type="radio" />
                    <span>很不方便</span>
                </label>
            </li>
        </ul>
    </div>
    <div class="survey_item">
        <h2>4.您认为手机天地哪些地方可以做得更好？（多选）</h2>
        <ul>
        	<li>
                <label>
                    <input value="" type="checkbox" />
                    <span>提供更清晰的手机筛选属性</span>
                </label>
            </li>
        	<li>
                <label>
                    <input value="" type="checkbox" />
                    <span>提升该页面的加载速度</span>
                </label>
            </li>
        	<li>
                <label>
                    <input value="" type="checkbox" />
                    <span>优化网站界面设计</span>
                </label>
            </li>
        	<li>
                <label>
                    <input value="" type="checkbox" />
                    <span>优化手机信息展示方式</span>
                </label>
            </li>
        	<li>
                <label>
                    <input value="" type="checkbox" />
                    <span>其他</span>
                </label>
            </li>
        </ul>
    </div>
    <div class="survey_item">
        <h2>5.您是否喜欢机荒网的色彩搭配？（单选）</h2>
        <ul>
        	<li>
                <label>
                    <input name="color" value="" type="radio" />
                    <span>非常喜欢</span>
                </label>
            </li>
        	<li>
                <label>
                    <input name="color" value="" type="radio" />
                    <span>一般</span>
                </label>
            </li>
        	<li>
                <label>
                    <input name="color" value="" type="radio" />
                    <span>不太喜欢</span>
                </label>
            </li>
        	<li>
                <label>
                    <input name="color" value="" type="radio" />
                    <span>很不喜欢</span>
                </label>
            </li>
        </ul>
    </div>
    <div class="survey_item">
        <h2>6.您在机荒网发布手机信息的经历如何？（单选）</h2>
        <ul>
        	<li>
                <label>
                    <input name="publish" value="" type="radio" />
                    <span>还没注册过帐号</span>
                </label>
            </li>
        	<li>
                <label>
                    <input name="publish" value="" type="radio" />
                    <span>注册过帐号但没发布过信息</span>
                </label>
            </li>
        	<li>
                <label>
                    <input name="publish" value="" type="radio" />
                    <span>发布信息次数3次（含）以下</span>
                </label>
            </li>
        	<li>
                <label>
                    <input name="publish" value="" type="radio" />
                    <span>发布信息次数3次以上</span>
                </label>
            </li>
        </ul>
    </div>
    <div class="survey_item">
        <h2>7.您的性别是？（单选）</h2>
        <ul>
        	<li>
                <label>
                    <input name="sex" value="" type="radio" />
                    <span>男</span>
                </label>
            </li>
        	<li>
                <label>
                    <input name="sex" value="" type="radio" />
                    <span>女</span>
                </label>
            </li>
        </ul>
    </div>
    <div class="survey_item">
        <h2>8.您的月收入范围为？（单选）</h2>
        <ul>
        	<li>
                <label>
                    <input name="income" type="radio" />
                    <span>2500以下</span>
                </label>
            </li>
        	<li>
                <label>
                    <input name="income" type="radio" />
                    <span>2500~4000</span>
                </label>
            </li>
        	<li>
                <label>
                    <input name="income" type="radio" />
                    <span>4000~6000</span>
                </label>
            </li>
        	<li>
                <label>
                    <input name="income" type="radio" />
                    <span>6000~8000</span>
                </label>
            </li>
        	<li>
                <label>
                    <input name="income" type="radio" />
                    <span>8000以上</span>
                </label>
            </li>
        </ul>
    </div>
    <div class="survey_item">
        <h2>9.您对机荒网页面有什么自己的看法？欢迎留下您的意见或建议。 （可选问答）</h2>
        <textarea></textarea>
    </div>
    <div class="survey_item">
        <h2>10.您愿意留下您的相关资料吗，以便我们诚邀你参加用户体验相关活动？ （可选问答）</h2>
        <table>
            <tr>
                <th>学历：</th>
                <td>
                    <input type="text" />
                </td>
            </tr>
            <tr>
                <th>年龄：</th>
                <td>
                    <input type="text" />
                </td>
            </tr>
            <tr>
                <th>网购年限：</th>
                <td>
                    <input type="text" />
                </td>
            </tr>
            <tr>
                <th>联系方式：</th>
                <td>
                    <input type="text" />
                </td>
            </tr>
        </table>
    </div>
	<button class="survey_submit" type="submit">提交</button>
    <div class="clear"></div>
    </form>
</div>