<?php global $MStatic;?>
<?php $brands = Factory::getView('system/mlib')->loadBrandList()?>
<script type="text/javascript">
jQuery(document).ready(function(){
	jQuery('.info_type').click(function(){
		jQuery('input[name=info_type]:checked').removeAttr('checked');
		jQuery(this).find('input[name=info_type]').attr('checked', 'checked');
		switch (jQuery(this).find('input[name=info_type]').val()) {
			case '1':
				window.location.href = '/customer/mobile/publish?cfrom=publish';
				break;
			case '0':
				window.location.href = '/customer/tablet/publish?cfrom=publish';
				break;
		}
	});
});
</script>
<table id="base_info" class="post_table">
	<tbody>
    	<tr>
        	<th><span class="red">*</span> 信息类型</th>
            <td>
            	<label class="info_type">
                	<input name="info_type" type="radio" checked="checked" value="1" />
                    <span>出售手机</span>
                </label>
            	<label class="info_type">
                	<input name="info_type" type="radio" value="0" />
                    <span>出售平板</span>
                </label>
            </td>
        </tr>
		<tr>
			<th><span class="red">*</span> 品牌</th>
			<td>
            	<select name="brand" class="default_selt" onchange="selectBrand(this);">
                	<option value="">请选择</option>
					<?php foreach ($brands as $key => $value):?>
					<option value="<?php echo $key?>"><?php echo $value?></option>
					<?php endforeach?>
                </select>
                <!--提示信息ks-->
                <div class="post_tis tis_brand">
                	<span class="empty">请选择品牌！</span>
                	<span class="right"></span>
                </div>
                <!--提示信息end-->
            </td>
		</tr>
		<tr class="mlist" style="display:none;">
			<th><span class="red">*</span> 型号</th>
			<td>
                <!--提示信息ks-->
                <div class="post_tis tis_xinghao">
                	<span class="empty">请选择型号！</span>
                	<span class="right"></span>
                </div>
                <!--提示信息end-->
            </td>
		</tr>
		<tr>
			<th>
				<span class="red">*</span> 上传图片
			</th>
			<td>
				<input type="hidden" name="thumb" value="" />
				<input type="hidden" name="gallery" value="" />
				<script type="text/javascript" src="<?php echo $this->getPlugin('swfupload/js/swfupload.js')?>"></script>
				<script type="text/javascript" src="<?php echo $this->getPlugin('swfupload/js/handlers.js')?>"></script>
				<script type="text/javascript">
					var swfu;
					window.onload = function () {
						swfu = new SWFUpload({
							// Backend Settings
							upload_url: "<?php echo $this->getUploadImgUrl()?>",
							post_params: {"PHPSESSID": "<?php echo session_id()?>"},
				
							// File Upload Settings
							file_size_limit : "5MB",	// 2MB
							file_types : "*.jpg;*.png;*.gif",
							file_types_description : "JPG/PNG/GIF Images",
							file_upload_limit : "10",
				
							// Event Handler Settings - these functions as defined in Handlers.js
							//  The handlers are not part of SWFUpload but are part of my website and control how
							//  my website reacts to the SWFUpload events.
							file_queue_error_handler : fileQueueError,
							file_dialog_complete_handler : fileDialogComplete,
							upload_progress_handler : uploadProgress,
							upload_error_handler : uploadError,
							upload_success_handler : uploadSuccess,
							upload_complete_handler : uploadComplete,
				
							// Button Settings
							button_image_url : "",
							button_placeholder_id : "spanButtonPlaceholder",
							button_width: 67,
							button_height: 26,
							button_text : '<div class="button"></div>',
							button_text_style : '.button {font-size: 12px;}',
							button_text_top_padding: 0,
							button_text_left_padding: 0,
							button_window_mode: SWFUpload.WINDOW_MODE.TRANSPARENT,
							button_cursor: SWFUpload.CURSOR.HAND,
							
							// Flash Settings
							flash_url : "<?php echo Factory::getBaseUrl()?>/plugin/swfupload/js/swfupload.swf",
				
							custom_settings : {
								upload_target : "upload-process"
							},
							
							// Debug Settings
							debug: false
						});
					};
				</script>
				<div class="upload_img">
					<form>
						<div class="upload_img_btn">
							<div id="spanButtonPlaceholder"></div>
						</div>
						<div style="float:left; line-height:30px; margin-left:10px;">最多上传10张图片，每张图片大小不能大于5M</div>
						<div class="clear"></div>
					</form>
					<div id="upload-process"></div>
					<div id="thumbnails" style="margin-top:5px;">
						<div class="clear"></div>
					</div>
				</div>
                <!--提示信息ks-->
                <div class="post_tis tis_upload_img">
                	<span class="error">请上传手机图片并选择信息封面图！</span>
                	<span class="right"></span>
                </div>
                <!--提示信息end-->
			</td>
		</tr>
		<tr>
			<th>手机状况</th>
			<td>
            	<div>
					<!--
					<input type="hidden" name="newly" value="" />
					-->
					<label onclick="isUsed(this);">
                        <input name="isnew" type="radio" value="0" />
                        <span>使用过</span>
                    </label>
                    <label onclick="isUsed(this);">
                        <input name="isnew" type="radio" value="1" />
                        <span>全新未拆封</span>
                    </label>
					<div class="clear"></div>
                </div>
                <!--提示信息ks-->
                <div class="post_tis tis_used">
                	<span class="focus">物品使用状况描述越详细效果越好喔！</span>
                	<span class="right"></span>
                </div>
                <!--提示信息end-->
            	<div class="sale_box used_sale_box">
                	<dl class="sale_box_item">
						<input type="hidden" name="screen" value="" />
                    	<dt>屏幕划痕或坏点</dt>
                        <dd>
							<?php foreach ($MStatic['screen'] as $key => $value):?>
							<a href="javascript:void(0);" onclick="describeScreen(this);" v="<?php echo $key?>"><?php echo $value?><i></i></a>
							<?php endforeach?>
							<div class="clear"></div>
                        </dd>
						<div class="clear"></div>
                    </dl>
                	<dl class="sale_box_item">
						<input type="hidden" name="pbody" value="" />
                    	<dt>机身磨损或划痕</dt>
                        <dd>
							<?php foreach ($MStatic['pbody'] as $key => $value):?>
							<a href="javascript:void(0);" onclick="describePbody(this);" v="<?php echo $key?>"><?php echo $value?><i></i></a>
							<?php endforeach?>
							<div class="clear"></div>
                        </dd>
						<div class="clear"></div>
                    </dl>
                	<dl class="sale_box_item">
                    	<dt>功能</dt>
                        <dd>
                        	<a href="javascript:void(0);" v="0" onclick="describeTrouble(this);">完全正常<i></i></a>
                        	<a href="javascript:void(0);" v="1" onclick="describeTrouble(this);">部分功能失灵<i></i></a>
							<div class="clear"></div>
                        </dd>
						<div class="clear"></div>
                    </dl>
                	<dl id="trouble_field" class="sale_box_item" style="height:80px;display:none;">
                    	<dt>描述失灵功能</dt>
                        <dd>
                        	<textarea name="trouble" placeholder="描述长度不能少于6个字，大于200个字" title="请描述失灵功能" value="描述长度不能少于6个字，大于200个字" onblur="describeTroubleNotwork(this);"></textarea>
                        </dd>
						<div class="clear"></div>
						<script type="text/javascript">
						jQuery(document).ready(function(){
							jQuery('textarea[name=trouble]').focus(function(){
								if (jQuery(this).val() == '描述长度不能少于6个字，大于200个字') {
									jQuery(this).val('');
								}
							});
							jQuery('textarea[name=trouble]').blur(function(){
								if (jQuery(this).val() == '') {
									jQuery(this).val('描述长度不能少于6个字，大于200个字');
								}
							});
						});
						</script>
                    </dl>
                	<dl class="sale_box_item">
						<input type="hidden" name="repair" value="" />
                    	<dt>维修史</dt>
                        <dd>
							<?php foreach ($MStatic['repair'] as $key => $value):?>
							<a href="javascript:void(0);" onclick="describeRepair(this);" v="<?php echo $key?>"><?php echo $value?><i></i></a>
							<?php endforeach?>
							<div class="clear"></div>
                        </dd>
						<div class="clear"></div>
                    </dl>
                	<dl class="sale_box_item">
						<input type="hidden" name="warranty" value="" />
                    	<dt>剩余保修期</dt>
                        <dd>
							<?php foreach ($MStatic['warranty'] as $key => $value):?>
							<a href="javascript:void(0);" onclick="describeWarranty(this);" v="<?php echo $key?>"><?php echo $value?><i></i></a>
							<?php endforeach?>
							<div class="clear"></div>
                        </dd>
						<div class="clear"></div>
                    </dl>
                	<dl class="sale_box_item sale_attachment" style="height:55px;">
                    	<dt>配件/发票</dt>
                        <dd>
							<?php foreach ($MStatic['attachment'] as $key => $value):?>
                        	<label>
								<input name="attachment" type="checkbox" value="<?php echo $key?>" />
								<span><?php echo $value?></span>
                            </label>
							<?php endforeach?>
							<div class="clear"></div>
                        </dd>
						<div class="clear"></div>
                    </dl>
					<script type="text/javascript">
					jQuery(document).ready(function(){
						jQuery('.sale_attachment label').click(function(){
							jQuery(this).parent().parent().css('background-color', 'white');
						});
					});
					</script>
                </div>
                <div class="sale_box new_sale_box">
                	<dl class="sale_box_item">
						<input type="hidden" name="warranty" value="" />
                    	<dt>剩余保修期</dt>
                        <dd>
							<?php foreach ($MStatic['warranty'] as $key => $value):?>
							<a href="javascript:void(0);" onclick="describeWarranty(this);" v="<?php echo $key?>"><?php echo $value?><i></i></a>
							<?php endforeach?>
							<div class="clear"></div>
                        </dd>
						<div class="clear"></div>
                    </dl>
                	<dl class="sale_box_item sale_attachment">
                    	<dt>配件/发票</dt>
                        <dd>
                        	<label>
								<input name="attachment" type="checkbox" value="1" />
								<span>正品发票</span>
                            </label>
                        	<label>
								<input name="attachment" type="checkbox" value="8" />
								<span>储存卡</span>
                            </label>
                        </dd>
						<div class="clear"></div>
                    </dl>
                </div>
            </td>
        </tr>
		<tr>
			<th><span class="red">*</span> 交易类型</th>
			<td>
            	<div class="trade_type">
                	<label onclick="chooseCost(this);">
						<input type="radio" name="cost" value="1" checked="checked" />
						<span>仅供购买</span>
                    </label>
                	<label onclick="chooseCost(this);">
						<input type="radio" name="cost" value="2" />
						<span>仅供换机</span>
                    </label>
                	<label onclick="chooseCost(this);">
						<input type="radio" name="cost" value="3" />
						<span>可购买、可换机</span>
                    </label>
                    <div class="clear"></div>
                </div>
                <div class="trade_price trade_box">
                	<div class="l">预售价格：</div>
                    <div class="r">
                    	<input type="text" name="price" value="" onfocus="checkMobileDescription();showMsg('price', 'focus');" />
                        <span>元</span>
                    </div>
                    <div class="clear"></div>
                </div>
                <div class="trade_exchange trade_box" style="display:none;">
                	<div class="l">换机条件：</div>
                    <div class="r">
                    	<textarea name="exchange" onfocus="checkMobileDescription();showMsg('tiaojian', 'focus');" placeholder="请输入6~50字之间的文字描述" title="请输入6~50字之间的文字描述"></textarea>
                    </div>
                    <div class="clear"></div>
                </div>
                <!--交易价格提示信息ks-->
                <div class="post_tis tis_price">
                	<span class="focus">只能填写整数，如1500</span>
                	<span class="empty">交易价格不能为空！</span>
                	<span class="error">格式错误，只能填写整数！</span>
                	<span class="right"></span>
                </div>
                <!--交易价格提示信息end-->
                <!--换机条件提示信息ks-->
                <div class="post_tis tis_tiaojian">
                	<span class="focus">6-50个字，请简单描述换机条件</span>
                	<span class="empty">换机条件不能为空！</span>
                	<span class="error">换机条件不能少于6个字，不能多于50个字！</span>
                	<span class="right"></span>
                </div>
                <!--换机条件提示信息end-->
            </td>
		</tr>
		<tr>
			<th><span class="red">*</span> 新旧程度</th>
			<td style="line-height: 30px;">
				<div>
					<div>
						<?php foreach ($MStatic['newly'] as $key => $value):?>
						<label>
							<input name="newly" type="radio" value="<?php echo $key?>" />
							<span><?php echo $value?></span>
						</label>
						<?php endforeach?>
					</div>
					<!--提示信息ks-->
					<div class="post_tis tis_newly" style="left: 430px;">
						<span class="error">请选择手机新旧程度！</span>
						<span class="right"></span>
					</div>
					<!--提示信息end-->
				</div>
            </td>
		</tr>
		<tr>
			<th><span class="red">*</span> 标题</th>
			<td style="line-height: 30px;">
				<!--
				<div style="float:left;">
					<span id="newly-label" class="red" style="font-size:14px;">[成色]</span>
				</div>
				<div style="float:left;">
					<input type="text" name="title" maxlength="50" value="" style="width:450px;" onfocus="checkCost();" />
					<div class="post_tis tis_title">
						<span class="focus">6-50个字，不能填写特殊字符</span>
						<span class="empty">标题不能为空！</span>
						<span class="error">标题不能少于6个字，多于50个字！</span>
						<span class="right"></span>
					</div>
				</div>
				<div class="clear"></div>
				-->
				<div>
					<input type="text" name="title" maxlength="50" value="" style="width:450px;" onfocus="checkCost();" />
					<!--提示信息ks-->
					<div class="post_tis tis_title">
						<span class="focus">6-50个字，不能填写特殊字符</span>
						<span class="empty">标题不能为空！</span>
						<span class="error">标题不能少于6个字，多于50个字！</span>
						<span class="right"></span>
					</div>
					<!--提示信息end-->
				</div>
            </td>
		</tr>
		<tr>
			<th><span class="red">*</span> 补充说明</th>
			<td>
            	<textarea class="supplement" name="remark" onfocus="checkTitle();"></textarea>
                <!--提示信息ks-->
                <div class="post_tis tis_miaoshu">
                	<span class="focus">10-2000个字，不能填写特殊字符</span>
                	<span class="empty">手机描述不能为空！</span>
                	<span class="error">手机描述不少于10个字，多于2000个字！</span>
                	<span class="right"></span>
                </div>
                <!--提示信息end-->
            </td>
		</tr>
		<tr>
			<th style="padding-top:20px;"><span class="red">*</span> 关于有效期</th>
			<td>
				<p>
					亲爱的用户，您所发布的信息<span class="red" style="font-weight:bold;">每24小时只能刷新一次</span>，如果您所发布的信息在<span class="red" style="font-weight:bold;">15天内</span>都没有进行刷新操作，系统会自动对您的信息进行过期处理，届时其他用户将不会看到您所发布的信息，您的过期信息将保存在“我发布的手机”栏目的过期信息中！
				</p>
            </td>
		</tr>
		<tr>
			<th></th>
			<td>
            	<a class="next_step_btn btn_blue" href="javascript:void(0);" onclick="checkRemark();">下一步，填写联系信息</a>
            </td>
		</tr>
	</tbody>
</table>
