<?php $id = Factory::getRequest()->getParam('id')?>
<?php $range = Factory::getRequest()->getParam('range', null)?>
<?php $page = Factory::getRequest()->getParam('p', 1)?>
<?php $per = 50?>
<ul class="tabs1">
	<li>基本信息</li>
	<li>设置密码</li>
	<li class="tabs1_c">操作历史</li>
</ul>
<div class="clear"></div>
<div class="tabs1_bd">
	<!--操作历史ks-->
	<div class="tabs1_item">
		<!--筛选框ks-->
		<div class="search_div">
			<form action="/monitor/system_member/operation" method="get">
				<div class="search_div_item">
					<input type="hidden" name="id" value="<?php echo $id?>" />
					<select name="range">
						<option value="0">全部</option>
						<option value="1" <?php echo $range == '1' ? 'selected="selected"' : ''?>>24小时内</option>
						<option value="2" <?php echo $range == '2' ? 'selected="selected"' : ''?>>72小时内</option>
						<option value="3" <?php echo $range == '3' ? 'selected="selected"' : ''?>>一周内</option>
						<option value="4" <?php echo $range == '4' ? 'selected="selected"' : ''?>>半个月内</option>
						<option value="5" <?php echo $range == '5' ? 'selected="selected"' : ''?>>一个月内</option>
					</select>
					<button type="submit">筛选</button>
				</div>
			</form>
		</div>
		<!--筛选框end-->
		<?php $operation = $this->loadMemberOperationList($id, $range, $page, $per)?>
		<div class="table1" entity="operation">
			<table width="990">
				<thead>
					<tr>
						<th width="300">动作</th>
						<th width="460">操作描述</th>
						<th width="200">操作时间</th>
					</tr>
				</thead>
				<tbody>
					<?php if ($operation):?>
					<?php foreach ($operation as $item):?>
					<tr>
						<td><?php echo $item['controller'] . '/' . $item['action']?></td>
						<td><?php echo $item['label']?></td>
						<td><?php echo date('Y-m-d H:i:s', $item['operated_at'])?></td>
					</tr>
					<?php endforeach?>
					<?php else:?>
					<tr>
						<td colspan="3" style="text-align:center;">暂无相关后台操作记录</td>
					</tr>
					<?php endif?>
				</tbody>
			</table>
		</div>
		<!--分页ks-->
		<?php $amount = $this->getMemberOperationTotal($id, $range)?>
		<?php if ($amount > $per):?>
		<?php $url = '/monitor/system_member/operation?id=' . $id . '&range=' . $range . '&'?> 
		<?php echo Factory::getView('page/paginator')->init($amount, $page, $per, $url, 'admin')->render();?>
		<?php endif?>
		<!--分页end-->
	</div>
	<!--操作历史end-->
</div>
<script type="text/javascript">
jQuery(document).ready(function(){
	jQuery('.tabs1 li').click(function(){
		var index = jQuery('.tabs1 li').index(jQuery(this));
		switch(index){
			case 0:
				window.location.href = '/monitor/system_member/info?id=<?php echo $id?>';
				break;
			case 1:
				window.location.href = '/monitor/system_member/pwd?id=<?php echo $id?>';
				break;
			case 2:
				break;
		}
	});
});
</script>
