<div class="store_biz_layout s_b_q" style="width:730px;height:200px;float:left;margin-right:20px;">
	<div class="store_biz_title">
		<h1>您的店铺有遇到以下烦恼么：</h1>
		<div class="clear"></div>
	</div>
	<div class="store_biz_content">
		<ul>
			<li>1、商品质量好、种类多，但<span class="red">难以接触到客户</span>？</li>
			<li>2、店铺服务又好又全面，却<span class="red">鲜有人问津</span>？</li>
			<li>3、<span class="red">促销活动宣传力度有限</span>？</li>
			<li>4、老客户认可度高，<span class="red">新用户却不知道</span>？</li>
		</ul>
	</div>
</div>
<div class="store_biz_layout" style="width:250px;height:200px;float:left;">
	<p style="font-size:14px;width:190px;margin:40px auto 20px;">了解更多机荒网线上店相关详情，请联系机荒网客服代表！</p>
	<div class="store_biz_link">
		<a target="_blank" href="http://wpa.qq.com/msgrd?v=3&uin=2824673297&site=www.mobilefrom.com&menu=yes">立即咨询了解</a>
	</div>
</div>
<div class="clear"></div>
<div class="store_biz_layout">
	<div class="store_biz_title">
		<h1>选择机荒网线上店吧！</h1>
		<p style="float:left;width:110px;"><a href="/website/store/customer?cfrom=store-business" target="_blank" style="font-size:14px;font-weight:normal;line-height:20px;">(什么是线上店?)</a></p>
		<div class="clear"></div>
	</div>
	<div class="store_biz_content s_b_good">
		<ul>
			<li>
				<h1 class="red">唯一专注数码交易</h1>
				<p>顺德唯一专注数码交易线上平台，提供买卖双方便捷的交流通道</p>
			</li>
			<li>
				<h1 class="red">推广无处不在</h1>
				<p>论坛推广、微博推广、微信推广、校园推广、活动推广... 您的潜在客户在哪，我们的推广就会出现在哪！</p>
			</li>
			<li>
				<h1 class="red">更容易达成交易</h1>
				<p>顺德各镇区域筛选、店铺服务筛选、手机销售型号筛选，让你的客户更容易找到您！</p>
			</li>
			<li>
				<h1 class="red">多种针对性推广手段</h1>
				<p>因为专注，所以专业，机荒网将根据数码交易行业的特殊性，配合各位商家推出各种针对性功能、活动页面等有效推广手段！</p>
			</li>
		</ul>
		<div class="clear"></div>
	</div>
</div>
<div class="store_biz_layout">
	<div class="store_biz_title">
		<h1 class="blue" style="text-align:center;float:none;">我们一直在进步，您的销售也会一同创新高！</h1>
	</div>
</div>
<div class="store_biz_layout">
	<div class="store_biz_title">
		<h1>商家入驻流程</h1>
		<div class="clear"></div>
	</div>
	<div class="store_biz_content" style="width:950px;margin:0 auto 20px;">
		<div class="store_biz_step">
			<div class="s_b_step1"></div>	
			<div class="s_b_step_title">提交认证资料</div>	
			<div class="s_b_step_content">
				<p>店主资料认证</p>
				<p>实体店铺、营业执照认证</p>
			</div>
		</div>
		<div class="store_biz_nstep"></div>
		<div class="store_biz_step">
			<div class="s_b_step2"></div>	
			<div class="s_b_step_title">完善店铺信息</div>	
			<div class="s_b_step_content">
				<p>根据实体店铺情况</p>
				<p>对应填写线上店的信息</p>
			</div>	
		</div>
		<div class="store_biz_nstep"></div>
		<div class="store_biz_step">
			<div class="s_b_step3"></div>	
			<div class="s_b_step_title">入驻成功</div>	
			<div class="s_b_step_content">
				<p>签订协议</p>
				<p>开放店铺</p>
			</div>	
		</div>
		<div class="clear"></div>
	</div>
</div>
<div class="store_biz_layout">
	<div class="store_biz_title">
		<h1>常见问题FAQ</h1>
		<div class="clear"></div>
	</div>
	<div class="store_biz_content s_b_faq">
		<ul>
			<li>
				<p><span class="red">Q1></span>入驻机荒网线上店有什么要求？<a class="blue" href="javascript:void(0);">收起</a></p>
				<ul class="s_b_faq_answer">
					<li>1、进驻商店必须承认只出售“零翻新、零组装、零假货、零山寨”数码产品；</li>
					<li>2、若商家出售翻新机、组装机、假货机、山寨机等问题机器，必需是顾客指定要求购买、买卖双方协商达成一致、顾客对所买产品情况已明确了解等情况，且必需在发票或收据等有效票据上标明此产品为翻新机、组装机、山寨机、假货机等字样。</li>
				</ul>
			</li>
			<li>
				<p><span class="red">Q2></span>入驻机荒网需要提供什么资料？<a class="blue" href="javascript:void(0);">收起</a></p>
				<ul class="s_b_faq_answer" style="display:none;">
					<li>1、店铺工商营业执照电子版（机荒网承诺绝对不向第三方泄漏相关资料）；</li>
					<li>2、店主联系方式，并验证店主身份信息（机荒网将有专人上门联系并确实店主身份）；</li>
					<li>3、店铺必须有实体店（机荒网将有专人上门拜访核实）。</li>
				</ul>
			</li>
			<li>
				<p><span class="red">Q3></span>如何确保商家的权利与责任？<a class="blue" href="javascript:void(0);">收起</a></p>
				<ul class="s_b_faq_answer" style="display:none;">
					<li>机荒网网站持有人将与店铺店主签订机荒网线上店使用协议。</li>
				</ul>
			</li>
			<li>
				<p><span class="red">Q4></span>假如商家进驻后被举报将如何处理？<a class="blue" href="javascript:void(0);">收起</a></p>
				<ul class="s_b_faq_answer" style="display:none;">
					<li>机荒网将协助举报人进行证据核实，并将相关证据提交机荒网监督组各成员，一经核实将立即取消该店铺与机荒网上的任何销售信息，并将相关举报信息置顶于机荒网举报中心首页，以示警告作用。详情请参考<a class="blue" href="/website/store/contract?cfrom=store-business">《机荒网线上店商家进驻协议》</a></li>
				</ul>
			</li>
		<ul>
	</div>
</div>
<script type="text/javascript">
jQuery(document).ready(function(){
	jQuery('.s_b_faq .blue').click(function(){
		if (jQuery(this).parent().parent().find('ul').css('display') == 'none') {
			jQuery(this).parent().parent().find('ul').slideDown();
		} else {
			jQuery(this).parent().parent().find('ul').slideUp();
		}
	});
});
</script>
<?php $stores = Factory::getView('store/list')->loadNewStoreList(6)?>
<?php if ($stores):?>
<div class="store_biz_layout">
	<div class="store_biz_title">
		<h1>最新入驻商家</h1>
		<a href="/store/list?cfrom=store-business">更多商家>></a>
		<div class="clear"></div>
	</div>
	<div class="store_biz_content s_b_list">
		<ul>
			<?php foreach ($stores as $store):?>
			<li>
				<div class="sthumb">
					<a href="/store/item/?store=<?php echo $store['id']?>&cfrom=store-business">
						<img src="http://mobilefrom-upload.stor.sinaapp.com/thumbnail/<?php echo $store['customer']?>.jpg" onerror="loadErrorStoreThumbnail(this);"/>
					</a>
				</div>
				<div class="sname">
					<a href="/store/item/?store=<?php echo $store['id']?>&cfrom=store-business"><?php echo $store['name']?></a>
				</div>
			</li>
			<?php endforeach?>
		</ul>
		<div class="clear"></div>
	</div>
</div>
<?php endif?>
<div class="store_biz_consult">
	<a target="_blank" href="http://wpa.qq.com/msgrd?v=3&uin=2824673297&site=www.mobilefrom.com&menu=yes">立即咨询了解</a>
</div>
