<div class="content" style="height:700px;">
    <h1>《机荒网线上店商家进驻协议》</h1>
	<p style="font-size:16px;line-height:30px;">1.商家开店必须提供以下真实资料（店铺名称、<span class="red">营业执照电子版</span>、店铺所在区域、店铺详细地址、店铺介绍、店铺相片、店主姓名、店主联系电话、店主联系QQ）。</p>
	<p style="font-size:16px;line-height:30px;">2.参与本项目的商家，必须出售<span class="red">零翻新机、零组装机、零山寨机</span>的数码产品（买家指定要求、买卖双方协商达成一致、买家对所买产品情况已明确了解除外，且必需在发票或收据上标明此产品为翻新机、组装机、山寨机等字样）。</p>
	<p style="font-size:16px;line-height:30px;">3.参加本项目商家，将具有本项目同行商家产品拆机、验机权利，即项目内商家的买家进行手机验机，本项目内的商家都有同等拆机、验机权利。<span class="red">拆机、验机过程必须全过程使用视频近距离记录，并在拆机前后出现买家影像，以防冒用。<span></p>
	<p style="font-size:16px;line-height:30px;">4.验机影像结果将发送项目监督组各成员（组内成员由全体项目商家及广大网友组成），成员将各自看法及评判依据汇总后得出结论将反馈买家，若举报属实，将按照本协议第5点处理方案执行。</p>
	<p style="font-size:16px;line-height:30px;">5.若商家在参与本项目过程中出售翻新机、组装机、山寨手机、假货手机（买家清楚情况除外），一经举报并证实属实，机荒网将<span class="red">即时屏蔽该商家所有相关销售信息</span>，并将于机荒网举报中心首页，将相关<span class="red">举报信息置顶</span>，以示警告。</p>
	<p style="font-size:16px;line-height:30px;">6.参加本项目的商家，机荒网将于“手机导购”、“本地商家”等板块显示商家及相关店铺销售信息。</p>
	<p style="font-size:16px;line-height:30px;">7.机荒网享有本协议相关条款最终解释权。</p>
</div>
