<div class="store_biz_layout s_c_q" style="width:730px;height:200px;float:left;margin-right:20px;">
	<div class="store_biz_title">
		<h1>购买数码产品，您是否遇到过以下烦恼：</h1>
		<div class="clear"></div>
	</div>
	<div class="store_biz_content">
		<ul>
			<li>1、不知道买什么牌子、什么型号会比较好？</li>
			<li>2、不知道去哪里买比较好，哪个商家可以相信呢？</li>
			<li>3、数码产品出现问题了，去哪里可以维修呢？</li>
			<li>4、哪里买手机可以分期付款？哪里可以回收二手数码产品？</li>
		</ul>
	</div>
</div>
<div class="store_biz_layout" style="width:250px;height:200px;float:left;">
	<div class="store_customer_link" style="margin:40px auto;">
		<a href="/website/store/business?cfrom=store-customer">商家入驻</a>
	</div>
	<div class="store_customer_link">
		<a href="/mlib/list?cfrom=store-customer">立即体验线上店</a>
	</div>
</div>
<div class="clear"></div>
<div class="store_biz_layout">
	<div class="store_biz_title">
		<h1>什么是线上店？</h1>
		<div class="clear"></div>
	</div>
	<div class="store_customer_content">
		<p>线上店是机荒网为了提供广大数码产品消费者<span class="red" style="font-weight:bold;">安心、快捷、方便</span>的线上服务。</p>
	</div>
</div>
<div class="store_biz_layout">
	<div class="store_biz_title">
		<h1>线上店有什么特别？</h1>
		<div class="clear"></div>
	</div>
	<div class="store_customer_content">
		<p>机荒网线上店服务由顺德本地手机数码<span class="red" style="font-weight:bold;">优质商家</span>（必须通过营业执照、店主身份证、实体店铺考察认证）组成，参与该服务商家必须遵守<span class="red" style="font-weight:bold;">“零翻新、零组装、零假货”</span>的“三零”销售原则，为广大数码产品消费者提供<span class="red" style="font-weight:bold;">安心、放心的数码产品消费环境</span>。</p>
	</div>
</div>
<div class="store_biz_layout">
	<div class="store_biz_title">
		<h1>怎么保证线上店商家出售商品都是“<span class="red">零翻新、零组装、零假货</span>”？</h1>
		<div class="clear"></div>
	</div>
	<div class="store_customer_content">
		<ul>
			<li>
				<h2 class="red">（1）强大、专业、开放的监督组织</h2>
				<p>“三零”服务的监督组织成员将由各线上店参与商家以及广大网友（自愿参与、网友或买家推荐等）组成。</p>
			</li>
			<li>
				<h2 class="red">（2）透明、公开的举报过程</h2>
				<p>用户如果怀疑自己在线上店的商家处购买了翻新机、组装机、山寨手机、假货手机等问题手机，携带有效单据、发票、手机、相关手机配件等到参与线上店的其它商家处进行检测，如检测过程中涉及拆机、验机等操作，必须使用视频记录整个拆机过程，并且为了避免冒充等情况发生，在拆机过程前后需要出现买家影像。</p>
			</li>
			<li>
				<h2 class="red">（3）权威、有力的举报结果</h2>
				<p>举报相关资料将发送到全体监督组织成员手上，机荒网将汇总各方的看法及评判依据反馈用户，若证实举报属实，机荒网将把相关举报资料发布上机荒网举报中心并将该信息置顶，此外还将即时移除该问题商家于机荒网的所有销售信息。</p>
			</li>
		</ul>
		<p style="font-size:14px;">注：交易过程中若商家出售翻新机、组装机、山寨手机、假货手机等问题手机，必须由买家指定要求、或买卖双方协商达成一致、或买家对所买产品情况已明确了解该情况，且商家必需在发票或收据上标明此产品为翻新机、组装机、山寨机、假货机等字样。</p>
	</div>
</div>
<div class="store_biz_consult">
	<a href="/mlib/list?cfrom=store-customer">立即体验线上店</a>
</div>
