<?php $id = Factory::getRequest()->getParam('id', null)?>
<?php $meta = $this->getStoreActivityMeta($id)?>
<title><?php echo $meta['store'] . '：' . $meta['title']?>-顺德手机优惠活动-机荒网</title>
<meta name="KEYWORDS" content='顺德手机优惠活动,顺德数码优惠活动,顺德同城购机,顺德手机导购,顺德手机,顺德手机交易,顺德二手手机,顺德闲置手机,佛山手机交易,佛山二手手机,机荒网' />
<meta name="DESCRIPTION" content='<?php echo $meta['title']?>,顺德手机优惠活动,顺德数码优惠活动,顺德同城购机,顺德手机导购' />
