<?php $order = Factory::getRequest()->getParam('order', '0')?>
<?php $groups = $this->loadAttributeGroupList($order)?>
<ul class="tabs1">
	<li>品牌列表</li>
	<li>属性列表</li>
	<li class="tabs1_c">属性组列表</li>
</ul>
<!--筛选框ks-->
<div class="search_div">
	<div class="search_div_item">
		<button type="button" onclick="window.location.href='/monitor/system_mlib/add-attribute-group'">+添加属性组</button>
	</div>
	<div class="search_div_item">
		<form action="/monitor/system_mlib/attribute-group-list" method="get">
			<strong>排序：</strong>
			<select name="order">
				<option value="0">创建时间</option>
				<option value="1" <?php echo $order ? 'selected="selected"' : ''?>>排序号</option>
			</select>
			<button type="submit">筛选</button>
		</form>
	</div>
	<div class="clear"></div>
</div>
<!--筛选框end-->
<div class="table1" entity="mlib-attribute-group">
	<table width="990">
		<thead>
			<tr>
				<th width="150">属性组名称</th>
				<th width="100">排序号</th>
				<th width="100">子属性数量</th>
				<th width="100">状态</th>
				<th class="tac" width="130">操作</th>
			</tr>
		</thead>
		<tbody>
			<?php if ($groups):?>
			<?php foreach ($groups as $group):?>
			<tr>
				<td><?php echo $group['label']?></td>
				<td><?php echo $group['sort']?></td>
				<td><?php echo $group['children']?></td>
				<td class="green"><?php echo $group['status'] ? '有效' : '冻结'?></td>
				<td class="table_cz tac">
					<a href="/monitor/system_mlib/add-attribute-group?id=<?php echo $group['id']?>">修改</a>
					<?php if ($group['status']):?>
					<a href="javascript:void(0);" onclick="itemInActive(this, '<?php echo $group['id']?>', 'mlib-attribute-group');">禁用</a>
					<?php else:?>
					<a href="javascript:void(0);" onclick="itemActive(this, '<?php echo $group['id']?>', 'mlib-attribute-group');">启用</a>
					<?php endif;?>
				</td>
			</tr>
			<?php endforeach?>
			<?php else:?>
			<tr>
				<td colspan="5" style="text-align:center;">暂无相关属性组记录</td>
			</tr>
			<?php endif?>
		</tbody>
	</table>
</div>
<script type="text/javascript">
jQuery(document).ready(function(){
	jQuery('.tabs1 li:eq(0)').click(function(){
		window.location.href = '/monitor/system_mlib/brand-list';
	});
	jQuery('.tabs1 li:eq(1)').click(function(){
		window.location.href = '/monitor/system_mlib/attribute-list';
	});
});
</script>
