<?php $page = Factory::getRequest()->getParam('p', '1')?>
<?php $reports = $this->loadMyReportList($page)?>
<div class="my_report_tit">
	<h2>我的举报</h2>
    <a class="blue" href="/website/report/list">返回举报中心>></a>
</div>
<table class="my_report_tb" width="740">
	<thead>
    	<tr>
        	<th width="450">举报标题</th>
        	<th width="150">举报类型</th>
        	<th width="150">状态</th>
        	<th width="150">操作</th>
        </tr>
    </thead>
    <tbody>
		<?php if ($reports):?>
		<?php $category = $this->getReportCategory()?>
		<?php foreach ($reports as $report):?>
    	<tr>
			<td><a href="/website/report/item?id=<?php echo $report['id']?>"><?php echo $report['title']?></a></td>
			<td><?php echo $category[$report['category_id']]?></td>
			<td class="red"><?php echo $report['status'] ? '显示中' : '已屏蔽'?></td>
			<td class="red"><a href="/website/report/publish?id=<?php echo $report['id']?>">修改</a></td>
        </tr>
		<?php endforeach?>
		<?php else:?>
        <tr>
        	<td colspan="4">
            	<p style="text-align:center; padding:30px 0px;">您暂时未举报过任何人！</p>
            </td>
        </tr>
		<?php endif?>
    </tbody>
	<?php $total = $this->getMyReportListTotal()?>
	<?php if ($total > 10):?>
	<?php $last = ceil($total / 10)?>
    <tfoot>
    	<tr>
        	<td colspan="4">
            	<!--分页ks-->
                <div class="fenye_wp">
                    <span>共<?php echo $total?>条举报</span>
					<?php if ($p != 1):?>
                    <a href="/website/report/my?p=<?php echo $page - 1?>"><</a>
					<?php endif?>
					<span><?php echo $page . '/' . $last?></span>
					<?php if ($p != $last):?>
					<a href="/website/report/my?p=<?php echo $page + 1?>">></a>
					<?php endif?>
                </div>
                <!--分页end-->
            </td>
        </tr>
    </tfoot>
	<?php endif?>
</table>
