<?php $id = Factory::getRequest()->getParam('id', null)?>
<?php $category = $this->getReportCategory()?>
<script type="text/javascript">
jQuery(document).ready(function(){
	<?php if ($id):?>
	getReport('<?php echo $id?>');
	<?php endif?>
	//去除粘帖内容中的所有标签
	jQuery('.report_edit').bind('paste', function(){
		var e = jQuery(this);
		setTimeout(function() {
			var content = jQuery(e).html();
			var re=/<[^img][^>]+>/g;
			content = content.replace(re,"");
			jQuery(e).html(content);
		}, 100);
	});
	jQuery('input[name=informer]').focus(function(){
		if (jQuery(this).val() == '被举报人的机荒网帐号') {
			jQuery(this).val('');
		}
	});
});
</script>
<div class="content">
	<input type="hidden" name="id" value="" />
	<div class="report_hd">
    	<h1>发布举报</h1>
    </div>
    <div class="report_bd">
    	<p class="title">标题 (5-50个字)：</p>
        <input name="title" class="title_input" type="text" style="font-size:18px;" maxlength="50" />
    	<p class="title" style="margin-top:25px;">事件陈述：</p>
        <!--文本编辑区域ks-->
        <div class="report_edit" contenteditable="true"></div>
        <!--文本编辑区域end-->
        <!--上传图片ks-->
        <div class="upload_img">
            <div>
                <span class="fs14">有图有真相：</span>
				<!--上传图片插件ks-->
				<input type="hidden" name="thumb" value="" />
				<input type="hidden" name="gallery" value="" />
				<script type="text/javascript" src="<?php echo $this->getPlugin('swfupload/js/swfupload.js')?>"></script>
				<script type="text/javascript" src="<?php echo $this->getPlugin('swfupload/js/report.js')?>"></script>
				<script type="text/javascript">
					var swfu;
					window.onload = function () {
						swfu = new SWFUpload({
							// Backend Settings
							upload_url: "<?php echo $this->getUploadImgUrl()?>",
							post_params: {"PHPSESSID": "<?php echo session_id()?>"},
				
							// File Upload Settings
							file_size_limit : "2 MB",	// 2MB
							file_types : "*.jpg;*.png;*.gif",
							file_types_description : "JPG/PNG/GIF Images",
							file_upload_limit : "0",
				
							// Event Handler Settings - these functions as defined in Handlers.js
							//  The handlers are not part of SWFUpload but are part of my website and control how
							//  my website reacts to the SWFUpload events.
							file_queue_error_handler : fileQueueError,
							file_dialog_complete_handler : fileDialogComplete,
							upload_progress_handler : uploadProgress,
							upload_error_handler : uploadError,
							upload_success_handler : uploadSuccess,
							upload_complete_handler : uploadComplete,
				
							// Button Settings
							button_image_url : "",
							button_placeholder_id : "spanButtonPlaceholder",
							button_width: 67,
							button_height: 26,
							button_text : '<div class="button"></div>',
							button_text_style : '.button {font-size: 12px;}',
							button_text_top_padding: 0,
							button_text_left_padding: 0,
							button_window_mode: SWFUpload.WINDOW_MODE.TRANSPARENT,
							button_cursor: SWFUpload.CURSOR.HAND,
							
							// Flash Settings
							flash_url : "<?php echo Factory::getBaseUrl()?>/plugin/swfupload/js/swfupload.swf",
				
							custom_settings : {
								upload_target : "upload-process"
							},
							
							// Debug Settings
							debug: false
						});
					};
				</script>
				<div class="upload_img">
					<form>
						<a id="upload_img_btn" href="javascript:void(0);">
							<div id="spanButtonPlaceholder"></div>
						</a>
						<span class="red">（上传图片更有说服力，如QQ对话截图等，每张图片大小不能大于2M）</span>
					</form>
					<div class="clear"></div>
					<div id="upload-process"></div>
					<div id="thumbnails" style="margin-top:5px;">
						<div class="clear"></div>
					</div>
				</div>
				<!--上传图片插件end-->
                <div class="clear"></div>
            </div>
        </div>
        <!--上传图片end-->
        <div class="report_btn">
        	<button class="delete" type="button" onclick="history.go(-1);">取消</button>
            <button class="publish" type="button" onclick="checkForm();">发布</button>
            <div class="clear"></div>
        </div>
    </div>
</div>
<?php $cfrom = Factory::getRequest()->getParam('cfrom', null)?>
<?php $tid = Factory::getRequest()->getParam('tid', null)?>
<?php $contact = $this->getInformerContact($tid, $cfrom)?>
<div class="sidebar">
    <div class="type">
        <span>类型</span>
        <select name="category" style="*width:158px;">
            <option value="">请选择举报类型</option>
			<?php foreach ($category as $key => $value):?>
			<option value="<?php echo $key?>"><?php echo $value?></option>
			<?php endforeach?>
        </select>
    </div>
    <div style="border-bottom:1px #fff solid; margin-bottom:20px; height:0px;"></div>
	<p>被举报人信息</p>
    <div class="input_item">
    	<i class="user"></i>
		<input class="bjbr" name="informer" value="<?php echo $contact['username'] ? $contact['username'] : '被举报人的机荒网帐号'?>" type="text" onblur="checkInformer(this);" style="color:#999" />
        <div class="clear"></div>
		<span class="informer_check" style="display:none;padding-left;"><span class="red">*</span>该帐号不存在，请确认输入是否正确，若非本站用户可忽略不填。</span>
    </div>
	<?php if ($contact['tel']):?>
    <div class="input_item">
    	<i class="mobile"></i>
        <div class="tag_wrap">
        	<div class="tag_list" style="display:block;">
				<p>
					<span><?php echo $contact['tel']?></span>
                    <a title="删除" href="javascript:void(0);" onclick="removeContactNumber(this, 'mtel');"></a>
                </p>
                <div class="clear"></div>
            </div>
        	<div class="iptwrap">
				<input name="tel" type="hidden" value="<?php echo $contact['tel']?>;" />
                <input name="mtel" placeholder="添加多个手机，回车确认" value="添加多个手机，回车确认" maxlength="11" style="color:#999" />
            </div>
        </div>
		<div class="clear"></div>
    </div>
	<?php else:?>
    <div class="input_item">
    	<i class="mobile"></i>
        <div class="tag_wrap">
        	<div class="tag_list">
                <div class="clear"></div>
            </div>
        	<div class="iptwrap">
				<input name="tel" type="hidden" value="" />
                <input name="mtel" placeholder="添加多个手机，回车确认" value="添加多个手机，回车确认" maxlength="11" style="color:#999" />
            </div>
        </div>
		<div class="clear"></div>
    </div>
	<?php endif?>
	<?php if ($contact['qq']):?>
    <div class="input_item">
    	<i class="qq"></i>
        <div class="tag_wrap">
        	<div class="tag_list" style="display:block;">
				<p>
					<span><?php echo $contact['qq']?></span>
                    <a title="删除" href="javascript:void(0);" onclick="removeContactNumber(this, 'mqq');"></a>
                </p>
                <div class="clear"></div>
            </div>
        	<div class="iptwrap">
				<input name="qq" type="hidden" value="<?php echo $contact['qq']?>;" />
                <input name="mqq" placeholder="添加多个qq号，回车确认" value="添加多个qq号，回车确认" maxlength="13" style="color:#999" />
            </div>
        </div>
		<div class="clear"></div>
    </div>
	<?php else:?>
    <div class="input_item">
    	<i class="qq"></i>
        <div class="tag_wrap">
        	<div class="tag_list">
                <div class="clear"></div>
            </div>
        	<div class="iptwrap">
				<input name="qq" type="hidden" value="" />
                <input name="mqq" placeholder="添加多个qq号，回车确认" value="添加多个qq号，回车确认" maxlength="13" style="color:#999" />
            </div>
        </div>
		<div class="clear"></div>
    </div>
	<?php endif?>
</div>
<div class="clear"></div>
