<?php $action = Factory::getRequest()->getActionName()?>
<?php 
switch ($action):
case 'what-to-buy':
?>
<title>【手机交易知多D】-顺德手机交易-机荒网</title>
<meta name="KEYWORDS" content='手机交易知多D,顺德手机交易,顺德二手手机,顺德闲置手机,佛山手机交易,佛山二手手机,机荒网' />
<meta name="DESCRIPTION" content='机荒网是佛山市顺德区专业的网上手机交易、手机信息共享平台。' />
<?php break?>
<?php case 'how-to-buy':?>
<title>【手机交易防骗攻略】-顺德手机交易-机荒网</title>
<meta name="KEYWORDS" content='手机交易防骗攻略,顺德手机交易,顺德二手手机,顺德闲置手机,佛山手机交易,佛山二手手机,机荒网' />
<meta name="DESCRIPTION" content='机荒网是佛山市顺德区专业的网上手机交易、手机信息共享平台。' />
<?php break?>
<?php case 'clean-private-info':?>
<title>【换手机之前清理手机隐私的5个步骤】-顺德手机交易-机荒网</title>
<meta name="KEYWORDS" content='清理手机隐私,换手机,顺德手机交易,顺德二手手机,顺德闲置手机,佛山手机交易,佛山二手手机,机荒网' />
<meta name="DESCRIPTION" content='机荒网是佛山市顺德区专业的网上手机交易、手机信息共享平台。' />
<?php break?>
<?php endswitch?>
