<?php $request = Factory::getRequest()?>
<?php $action = $request->getActionName()?>
<?php $id = $request->getParam('id', null)?>
<?php 
switch ($action):
case 'list':
?>
<title>【<?php echo $id ? $this->getReportCategory($id) : '举报中心'?>】-【手机交易举报】-顺德手机交易-机荒网</title>
<meta name="KEYWORDS" content='手机交易举报,顺德手机交易,顺德二手手机,顺德闲置手机,佛山手机交易,佛山二手手机,机荒网' />
<meta name="DESCRIPTION" content='机荒网是佛山市顺德区专业的网上手机交易、手机信息共享平台。' />
<?php break?>
<?php case 'item':?>
<?php $title = $id ? $this->getReportTitle($id) : ''?>
<title><?php echo $title ? '【' . $title . '】-' : ''?>【手机交易举报】-顺德手机交易-机荒网</title>
<meta name="KEYWORDS" content='<?php echo $title . ','?>手机交易举报,顺德手机交易,顺德二手手机,顺德闲置手机,佛山手机交易,佛山二手手机,机荒网' />
<meta name="DESCRIPTION" content='机荒网是佛山市顺德区专业的网上手机交易、手机信息共享平台。' />
<?php break?>
<?php case 'publish':?>
<title>【发布举报】-【手机交易举报】-顺德手机交易-机荒网</title>
<meta name="KEYWORDS" content='发布举报,手机交易举报,顺德手机交易,顺德二手手机,顺德闲置手机,佛山手机交易,佛山二手手机,机荒网' />
<meta name="DESCRIPTION" content='机荒网是佛山市顺德区专业的网上手机交易、手机信息共享平台。' />
<?php break?>
<?php case 'my':?>
<title>【我的举报】-【手机交易举报】-顺德手机交易-机荒网</title>
<meta name="KEYWORDS" content='我的举报,手机交易举报,顺德手机交易,顺德二手手机,顺德闲置手机,佛山手机交易,佛山二手手机,机荒网' />
<meta name="DESCRIPTION" content='机荒网是佛山市顺德区专业的网上手机交易、手机信息共享平台。' />
<?php break?>
<?php case 'rule':?>
<title>【举报规则】-【手机交易举报】-顺德手机交易-机荒网</title>
<meta name="KEYWORDS" content='举报规则,手机交易举报,顺德手机交易,顺德二手手机,顺德闲置手机,佛山手机交易,佛山二手手机,机荒网' />
<meta name="DESCRIPTION" content='机荒网是佛山市顺德区专业的网上手机交易、手机信息共享平台。' />
<?php break?>
<?php endswitch?>
