<?php $q = Factory::getRequest()->getParam('q', null)?>
<div class="mlib_list_select_area mlib_list_layout">
	<div class="m_l_s_a_selector">
		<dl class="m_l_s_a_s_item" style="font-size:14px;">
			<dt>搜索内容：</dt>
			<dd>
				<ul>
					<li><span class="red" style="font-weight:bold;"><?php echo $q?></span></li>
				</ul>
				<div class="clear"></div>
			</dd>
			<div class="clear"></div>
		</dl>
		<?php $filter = $this->loadFilterOptionList()?>
		<dl class="m_l_s_a_s_item">
			<dt>手机品牌：</dt>
			<dd>
				<ul>
					<li><a class="selected" href="/mlib/list?filter[brand]=all">不限</a></li>
					<?php foreach ($filter['brand'] as $key => $value):?>
					<li><a href="/mlib/list?filter[brand]=<?php echo $key?>"><?php echo $value?></a></li>
					<?php endforeach?>
				</ul>
				<div class="clear"></div>
			</dd>
			<div class="clear"></div>
		</dl>
		<dl class="m_l_s_a_s_item">
			<dt>价格范围：</dt>
			<dd>
				<ul style="float:left;">
					<li><a class="selected" href="/mlib/list?filter[price]=all">不限</a></li>
					<?php foreach ($filter['price'] as $key => $value):?>
					<li><a href="/mlib/list?filter[price]=<?php echo $key?>"><?php echo $value['label']?></a></li>
					<?php endforeach?>
				</ul>
				<div class="clear"></div>
			</dd>
			<div class="clear"></div>
		</dl>
		<dl class="m_l_s_a_s_item">
			<dt>操作系统：</dt>
			<dd>
				<ul>
					<li><a class="selected" href="/mlib/list?filter[os]=all">不限</a></li>
					<?php foreach ($filter['os'] as $key => $value):?>
					<li><a href="/mlib/list?filter[os]=<?php echo $key?>"><?php echo $value?></a></li>
					<?php endforeach?>
				</ul>
				<div class="clear"></div>
			</dd>
			<div class="clear"></div>
		</dl>
	</div>
</div>
<div class="mlib_list_item_area mlib_list_layout">
	<?php $models = $this->loadModelSearchList($q)?>
	<?php if ($models):?>
	<ul>
		<?php foreach ($models as $key => $model):?>
		<li id="m_l_i_<?php echo $model['id']?>" v="<?php echo $model['id']?>" <?php echo ($key + 1) % 4 == 0 ? 'class="m_l_i_a_wrap"' : ''?>>
			<div class="m_l_i_a_thumb m_l_i_a_item_layout">
				<a href="/mlib/item?id=<?php echo $model['id']?>&cfrom=list" target="_blank">
					<img src="<?php echo $this->getThumbImg($model['thumb'])?>" onerror="loadErrorImg(this);" />
				</a>
			</div>
			<div class="m_l_i_a_title m_l_i_a_item_layout">
				<a href="/mlib/item?id=<?php echo $model['id']?>&cfrom=list" target="_blank" title="<?php echo $model['brand'] . ' ' . $model['model']?>"><?php echo $model['brand'] . ' ' . $model['model']?></a>
			</div>
			<div class="m_l_i_a_price m_l_i_a_item_layout">
				<div class="m_l_i_a_left">
					<span>新机：暂无出售</span>
				</div>
				<div class="m_l_i_a_right">
					<span>二手：暂无出售</span>
				</div>
				<div class="clear"></div>
			</div>
			<div class="m_l_i_a_sells m_l_i_a_item_layout">
				<div class="m_l_i_a_left">
					<span><?php echo $model['offers'] ? '<span class="red">' . $model['offers'] . '</span>' : '0'?>条出售信息</span>
				</div>
				<div class="m_l_i_a_right">
					<span><?php echo $model['clicks']?>次点阅</span>
				</div>
				<div class="clear"></div>
			</div>
		</li>
		<?php endforeach?>
	</ul>
	<div class="clear"></div>
	<?php else:?>
	<div style="text-align:center;font-size:16px;">暂无相关手机信息</div>
	<?php endif?>
	<div class="clear"></div>
</div>
<script type="text/javascript">
jQuery(document).ready(function(){
	var mdata = new Array();
	jQuery('.mlib_list_item_area ul li').each(function(){
		mdata.push(jQuery(this).attr('v'));
	});
	loadModelQuote(mdata);
	jQuery('.mlib_list_order_area ul li').click(function(){
		window.location.href = jQuery(this).find('a').attr('href');
	});
});
</script>
