<?php $services = $this->loadServiceList()?>
<div class="search_div">
	<div class="search_div_item">
		<button type="button" onclick="window.location.href='/monitor/system_service/add'">添加服务</button>
	</div>
	<div class="clear"></div>
</div>
<div class="table1" entity="service">
	<table width="990">
		<thead>
			<tr>
				<th style="width:150px;">服务ID</th>
				<th style="width:150px;">服务名称</th>
				<th>服务描述</th>
				<th class="tac" style="width:150px;">操作</th>
			</tr>
		</thead>
		<tbody>
			<?php if ($services):?>
			<?php foreach ($services as $service):?>
			<tr>
				<td><?php echo $service['id']?></td>
				<td><?php echo $service['title']?></td>
				<td><?php echo $service['description']?></td>
				<td class="table_cz tac">
					<a href="/monitor/system_service/add?id=<?php echo $service['id']?>">修改</a>
				</td>
			</tr>
			<?php endforeach?>
			<?php else:?>
			<tr>
				<td colspan="6" style="text-align:center;">暂无符合条件的服务记录</td>
			</tr>
			<?php endif?>
		</tbody>
	</table>
</div>
