<!--发布失败ks-->
<div id="publish_fail" class="alert_box" style="width:240px; height:115px;margin: -57px 0 0 -120px;display:none;z-index:99;">
	<div class="alert_title">
		<h3>发布失败</h3>
		<a href="javascript:void(0);" onclick="closeAlter(this);"></a>
		<div class="clear"></div>
	</div>
	<div class="alert_content" style="height:65px;">
		<i>
			<img src="<?php echo $this->getImg('delete3.png')?>" />
		</i>
		<p style="width:180px;">
			失败原因：
			<span class="grey">服务器忙，请稍后再试!</span>
		</p>
		<div class="clear"></div>
	</div>
</div>
<!--发布失败end-->
<script type="text/javascript">
jQuery(document).ready(function(){
	jQuery('.alert_content i').click(function(){
		jQuery('#publish_fail').hide();
	});
});
</script>
