<?php $store = Factory::getRequest()->getParam('store', null)?>
<?php $sina = $this->getSinaAccount($store)?>
<?php $sina = $sina ? '&ralateuid=' . $sina : ''?>
<script type="text/javascript">
(function(){
var url = "http://widget.weibo.com/distribution/comments.php?width=0&url=http%3A%2F%2Fwww.mobilefrom.com%2Fstore%2Fitem%3Fstore%3D<?php echo $store . $sina?>&appkey=2782468044&dpc=1";
document.write('<iframe id="WBCommentFrame" src="' + url + '" scrolling="no" frameborder="0" style="width:100%"></iframe>');
})();
</script>
<script src="http://tjs.sjs.sinajs.cn/open/widget/js/widget/comment.js" type="text/javascript" charset="utf-8"></script>
<script type="text/javascript">
window.WBComment.init({
    "id": "WBCommentFrame"
});
</script>
