<?php $store = Factory::getRequest()->getParam('store', null)?>
<?php $services = $this->loadStoreServiceTitleList($store)?>
<?php $mobiles = $this->loadSellingMobileModelList($store, '1', '8')?>
<?php $tablets = $this->loadSellingTabletModelList($store, '1', '8')?>
<?php $activity = $this->getStoreActivity($store)?>
<?php if ($activity):?>
<div class="activity">
	<span class="red">优惠活动：</span>
	<a title="<?php echo $activity['title']?>" href="/activity/item/store?cfrom=store&id=<?php echo $activity['id']?>"><?php echo $activity['title']?></a>
</div>
<?php endif?>
<?php if ($services):?>
<div class="store_service">
	<ul>
		<?php foreach ($services as $item):?>
		<li>
			<a href="/store/item/service?cfrom=store-index&store=<?php echo $store?>"><?php echo $item['title']?></a>
		</li>
		<?php endforeach?>
	</ul>
	<div class="more_service">
		<a href="/store/item/service?cfrom=store-index&store=<?php echo $store?>">查看本店全部服务 >></a>
	</div>
</div>
<?php endif?>
<div class="store_new">
	<div class="store_new_title"></div>
	<!--商品列表ks-->
	<div class="pro_list">
		<ul>
			<?php if ($mobiles):?>
			<?php foreach ($mobiles as $model):?>
			<li>
				<a class="pro_wp" title="<?php echo $model['brand'] . '&nbsp;' . $model['model']?>" href="/store/item/mobile-info?store=<?php echo $store?>&model=<?php echo $model['id']?>&cfrom=store-model">
					<div class="pro_img">
						<img src="http://mobilefrom-upload.stor.sinaapp.com/mlib/thumb/<?php echo $model['thumb']?>" onerror="loadErrorImg(this);" />
					</div>
					<p class="pro_name"><?php echo $model['brand'] . '&nbsp;' . $model['model']?></p>
				</a>
				<p class="pro_price">
					<?php if ($model['min'] == $model['max']):?>
					<span class="red">￥<?php echo $model['max']?></span>
					<?php else:?>
					<span class="red">￥<?php echo $model['min']?></span>
					<em>~</em>
					<span class="red">￥<?php echo $model['max']?></span>
					<?php endif?>
				</p>
			</li>
			<?php endforeach?>
			<?php endif?>
			<?php if ($tablets):?>
			<?php foreach ($tablets as $model):?>
			<li>
				<a class="pro_wp" title="<?php echo $model['brand'] . '&nbsp;' . $model['model']?>" href="/store/item/tablet-info?store=<?php echo $store?>&model=<?php echo $model['id']?>&cfrom=store-model">
					<div class="pro_img" style="padding:50px 10px 49px;">
						<img src="http://mobilefrom-upload.stor.sinaapp.com/tlib/thumb/<?php echo $model['thumb']?>" onerror="loadErrorImg(this);" style="height:151px;" />
					</div>
					<p class="pro_name"><?php echo $model['brand'] . '&nbsp;' . $model['model']?></p>
				</a>
				<p class="pro_price">
					<?php if ($model['min'] == $model['max']):?>
					<span class="red">￥<?php echo $model['max']?></span>
					<?php else:?>
					<span class="red">￥<?php echo $model['min']?></span>
					<em>~</em>
					<span class="red">￥<?php echo $model['max']?></span>
					<?php endif?>
				</p>
			</li>
			<?php endforeach?>
			<?php endif?>
		</ul>
		<div class="clear"></div>
	</div>
	<!--商品列表end-->
</div>
<script type="text/javascript">
jQuery(document).ready(function(){
	jQuery('.store_service ul li:eq(0)').css('background-color', '#FF6600');
	jQuery('.store_service ul li:eq(1)').css('background-color', '#0066FF');
	jQuery('.store_service ul li:eq(2)').css('background-color', '#669900');
	jQuery('.store_service ul li:eq(3)').css('background-color', '#CC0066');
	jQuery('.store_service ul li:eq(4)').css('background-color', '#CC0000');
	jQuery('.store_service ul li:eq(5)').css('background-color', '#333333');
});
</script>
