<?php $module = Factory::getRequest()->getParam('module')?>
<?php $range = Factory::getRequest()->getParam('range', '1')?>
<?php $records = $this->modulePageFrom($module, $range)?>
<?php $total = $records['total']?>
<?php unset($records['total'])?>
<!--筛选框ks-->
<div class="search_div">
	<div class="search_div_item">
		<form action="/monitor/analysis_pfrom/module" method="get">
			<strong>模块：<?php echo $module?></strong>
			<strong>统计范围：</strong>
			<select name="range">
				<option value="1" <?php echo $range == '1' ? 'selected="selected"' : ''?>>今天数据</option>
				<option value="2" <?php echo $range == '2' ? 'selected="selected"' : ''?>>昨天数据</option>
				<option value="3" <?php echo $range == '3' ? 'selected="selected"' : ''?>>三天内数据</option>
				<option value="4" <?php echo $range == '4' ? 'selected="selected"' : ''?>>一周内数据</option>
				<option value="5" <?php echo $range == '5' ? 'selected="selected"' : ''?>>全部数据</option>
			</select>
			<input type="hidden" name="module" value="<?php echo $module?>" />
			<button type="submit">筛选</button>
		</form>
	</div>
	<div class="clear"></div>
</div>
<!--筛选框end-->
<div class="table1" entity="pfrom-module">
	<table width="990">
		<thead>
			<tr>
				<th width="150">url</th>
				<th width="150">站外数量</th>
				<th width="150">站外比例</th>
				<th width="150">站内数量</th>
				<th width="150">站内比例</th>
				<th width="150">页面比例</th>
				<th width="90">操作</th>
			</tr>
		</thead>
		<tbody>
			<?php if ($records):?>
			<?php foreach ($records as $url => $record):?>
			<tr>
				<td><?php echo $url?></td>
				<td><?php echo $record['outside']?></td>
				<td><?php echo ceil($record['outside'] / $record['subtotal'] * 100)?>%</td>
				<td><?php echo $record['inside']?></td>
				<td><?php echo ceil($record['inside'] / $record['subtotal'] * 100)?>%</td>
				<td><?php echo ceil($record['subtotal'] / $total * 100)?>%</td>
				<td>
					<a href="/monitor/analysis_pfrom/action?action=<?php echo $module . '_' . $url?>&range=<?php echo $range?>">查看</a>
				</td>
			</tr>
			<?php endforeach?>
			<?php else:?>
			<tr>
				<td colspan="7" style="text-align:center;">暂未对应的导向统计数据</td>
			</tr>
			<?php endif?>
		</tbody>
	</table>
</div>
