<!--第一屏ks-->
<div class="first_screen">
	<!--相册ks-->
	<div class="index_gallery">
    	<ul class="gallery_img">
        	<li>
            	<a href="/website/store/business?cfrom=index"><img src="<?php echo $this->getImg('home/1.jpg')?>" /></a>
            </li>
            <div class="clear"></div>
        </ul>
    </div>
    <!--相册end-->
    <!--为什么选择机荒网ks-->
    <div class="choose_reason">
    	<div class="c_reason_hd">
        	<p>为什么选择机荒网？</p>
            <ul class="date">
            	<li>日用户量：92</li>
            	<li>日点击量：1003</li>
            	<li>总点击量：<?php echo 49652 + 85819?></li>
            </ul>
            <div class="clear"></div>
        </div>
        <ul class="c_reason_bd">
        	<li>
            	<p>质量保证</p>
                <p class="grey1" style="margin-top:10px;">零翻新、零组装、零假货，机荒网认证商家让您购机无忧！</p>
            </li>
        	<li>
            	<p>快捷高效</p>
                <p class="grey1" style="margin-top:10px;">品牌、地区、价格、型号筛选，帮你快速找到合心意的手机信息。</p>
            </li>
        	<li>
            	<p>方便省心</p>
                <p class="grey1" style="">无需频繁顶贴、发布操作简单、一键QQ交谈更快与买家取得联系。</p>
            </li>
            <div class="clear"></div>
        </ul>
    </div>
    <!--为什么选择机荒网end-->
</div>
<!--第一屏end-->

<!--优惠活动ks-->
<?php $activity = Factory::getView('activity/list')->loadNewStoreActivityList(2)?>
<div class="floor" style="display:none;">
    <div class="hd">
        <h1><a class="red" href="/activity/list/store?cfrom=index">最新优惠活动</a></h1>
        <a class="next_set" href="/activity/list/store?cfrom=index">更多优惠活动</a>
        <div class="clear"></div>
    </div>
    <div class="bd">
		<div class="activity-wp">
			<?php foreach ($activity as $item):?>
			<div class="activity">
				<div class="a-l-title">
					<a href="/activity/item/store?cfrom=index&id=<?php echo $item['id']?>" title="<?php echo $item['title']?>"><?php echo $item['title']?></a>
				</div>
				<div class="a-l-detail">
					<div class="a-l-thumb">
						<img src="http://mobilefrom-upload.stor.sinaapp.com/store/thumb/<?php echo $item['thumb']?>" onerror="loadErrorImg(this);" />
					</div>
					<div class="a-l-info">
						<div class="a-l-i-summary">
							<p><?php echo $item['description']?></p>
						</div>
						<div class="a-l-i-bottom">
							<div class="a-l-i-date">
								<span>距离结束还有：</span>
								<span class="red"><?php echo $item['limit']?></span>
							</div>
							<div class="a-l-i-link">
								<a href="/activity/item/store?cfrom=index&id=<?php echo $item['id']?>">查看活动详情>></a>
							</div>
							<div class="clear"></div>
						</div>
					</div>
					<div class="clear"></div>
				</div>
			</div>
			<?php endforeach?>
			<div class="clear"></div>
		</div>
    </div>
</div>
<!--优惠活动end-->
<!--手机导购ks-->
<?php $mobiles = Factory::getView('mlib/list')->loadHotModelList(1, 10)?>
<?php $mtop = array_slice($mobiles, 0, 5)?>
<?php $mbottom = array_slice($mobiles, 5)?>
<div class="floor">
    <div class="hd">
        <h1><a href="/mlib/list?cfrom=index_hot">1F 热门手机</a></h1>
        <a class="next_set" href="/mlib/list?cfrom=index_hot">查看更多</a>
        <div class="clear"></div>
    </div>
    <div class="bd">
		<?php if ($mobiles):?>
    	<div class="mlib_list">
            <ul>
				<?php foreach ($mtop as $item):?>
                <li>
                    <a class="mlib_img_name" href="/mlib/item?id=<?php echo $item['id']?>&cfrom=index_hot" title="<?php echo $item['brand'] . ' ' . $item['model']?>">
                        <img src="http://mobilefrom-upload.stor.sinaapp.com/mlib/thumb/<?php echo $item['thumb']?>" onerror="loadErrorImg(this);" title="<?php echo $item['brand'] . ' ' . $item['model']?>" />
                        <span title="<?php echo $item['brand'] . ' ' . $item['model']?>"><?php echo $item['brand'] . ' ' . $item['model']?></span>
                    </a>
                    <p class="mlib_price_time">
                        <span class="mlib_price grey1"><span class="red"><?php echo $item['offers']?></span>条出售信息</span>
                        <span class="mlib_time grey1"><span class="red"><?php echo $item['clicks']?></span>次点阅量</span>
                        <div class="clear"></div>
                    </p>
                </li>
				<?php endforeach?>
				<div class="clear"></div>
            </ul>
        </div>
        <div class="mlib_down_list">
            <ul>
				<?php foreach ($mbottom as $item):?>
                <li>
                    <a class="l" href="/mlib/item?id=<?php echo $item['id']?>&cfrom=index_hot" title="<?php echo $item['brand'] . ' ' . $item['model']?>">
                    	<img src="http://mobilefrom-upload.stor.sinaapp.com/mlib/thumb/<?php echo $item['thumb']?>" onerror="loadErrorImg(this);" title="<?php echo $item['brand'] . ' ' . $item['model']?>" />
                    </a>
                    <div class="r">
                    	<a href="/mlib/item?id=<?php echo $item['id']?>&cfrom=index_hot" title="<?php echo $item['brand'] . ' ' . $item['model']?>"><?php echo $item['brand'] . ' ' . $item['model']?></a>
                        <p class="grey"><span class="red"><?php echo $item['offers']?></span>条出售信息</p>
                        <p class="grey"><span class="red"><?php echo $item['clicks']?></span>次点阅量</p>
                    </div>
                    <div class="clear"></div>
                </li>
				<?php endforeach?>
				<div class="clear"></div>
            </ul>
        </div>
		<?php endif?>
    </div>
</div>
<!--手机导购end-->
<!--平板导购ks-->
<?php $tablets = Factory::getView('tlib/list')->loadHotModelList(1, 10)?>
<?php $ttop = array_slice($tablets, 0, 5)?>
<div class="floor">
    <div class="hd" style="*padding-top:20px;">
        <h1><a href="/tlib/list?cfrom=index_hot">2F 热门平板</a></h1>
        <a class="next_set" href="/tlib/list?cfrom=index_hot">查看更多</a>
        <div class="clear"></div>
    </div>
    <div class="bd">
		<?php if ($tablets):?>
    	<div class="mlib_list">
            <ul>
				<?php foreach ($ttop as $item):?>
                <li style="height:196px;">
                    <a class="mlib_img_name" href="/tlib/item?id=<?php echo $item['id']?>&cfrom=index_hot" title="<?php echo $item['brand'] . ' ' . $item['model']?>">
                        <img style="height:auto;" src="http://mobilefrom-upload.stor.sinaapp.com/tlib/thumb/<?php echo $item['thumb']?>" onerror="loadErrorImg(this);" title="<?php echo $item['brand'] . ' ' . $item['model']?>" />
                        <span title="<?php echo $item['brand'] . ' ' . $item['model']?>"><?php echo $item['brand'] . ' ' . $item['model']?></span>
                    </a>
                    <p class="mlib_price_time">
                        <span class="mlib_price grey1"><span class="red"><?php echo $item['offers']?></span>条出售信息</span>
                        <span class="mlib_time grey1"><span class="red"><?php echo $item['clicks']?></span>次点阅量</span>
                        <div class="clear"></div>
                    </p>
                </li>
				<?php endforeach?>
				<div class="clear"></div>
            </ul>
        </div>
		<?php endif?>
    </div>
</div>
<!--平板导购end-->
<!--本地商家ks-->
<?php $stores = Factory::getView('store/list')->loadNewStoreList()?>
<div class="floor">
    <div class="hd" style="*padding-top:20px;">
        <h1><a href="/store/list?cfrom=index">3F 本地最新入驻商家</a></h1>
        <a class="next_set" href="/store/list?cfrom=index">更多商家</a>
        <div class="clear"></div>
    </div>
    <div class="bd store_wp">
        <div class="store_list">
            <ul>
				<?php foreach ($stores as $id => $store):?>
                <li>
                    <div class="business_img">
                        <a href="/store/item/?store=<?php echo $id?>&cfrom=index">
                            <img src="http://mobilefrom-upload.stor.sinaapp.com/thumbnail/<?php echo $store['customer']?>.jpg" onerror="loadErrorStoreThumbnail(this);"/>
                        </a>
                    </div>
					<p>[<span class="red"><?php echo implode('、', array_unique($store['region']))?></span>]<?php echo $store['name']?></p>
                </li>
                <?php endforeach?>
				<li>
					<div class="business_img business_add">
						<a href="/website/store/business?cfrom=index"></a>
					</div>
					<p style="text-align:center;">
						我是商家，<a class="blue" href="/website/store/business?cfrom=index">我要入驻</a>
					</p>
				</li>
            </ul>
			<div class="clear"></div>
        </div>
    </div>
</div>
<!--本地商家end-->
<!--举报中心ks-->
<?php $reports = Factory::getView('website/report')->loadThumbnailReportList(1, 5)?>
<div class="floor">
    <div class="hd">
        <h1><a href="/website/report/list?cfrom=index">4F 举报经典案例</a></h1>
        <a class="next_set" href="/website/report/list?cfrom=index">查看全部</a>
    </div>
    <div class="bd z_report">
        <ul class="article_list">
            <?php foreach ($reports as $item):?>
            <li>
                <div class="article_img">
                    <a href="/website/report/item?cfrom=index&id=<?php echo $item['id']?>" target="_blank">
                        <img src="http://mobilefrom-upload.stor.sinaapp.com/report/thumb/<?php echo $item['thumb']?>" onerror="loadErrorImg(this);"/>
                    </a>
                </div>
                <p>
                    <a href="/website/report/item?cfrom=index&id=<?php echo $item['id']?>" title="<?php echo $item['title']?>" target="_blank">
                        <?php echo $item['title']?>
                    </a>
                </p>
            </li>
            <?php endforeach?>
        	<div class="clear"></div>
        </ul>
    </div>
</div>
<!--举报中心end-->

<div class="join_weibo">
	<!--加入机荒网ks-->
    <div class="join_mf">
        <h1>加入机荒网</h1>
        <p style="margin-top:16px;">现在加入机荒网，享受安全、放心的数码交易体验...</p>
		<?php if (Factory::isLoged()):?>
        <div class="login_method">
            <a href="/customer">
                <img src="<?php echo $this->getImg('home/zh_sina.jpg')?>" />
            </a>
            <a href="/customer">
                <img src="<?php echo $this->getImg('home/zh_qq.jpg')?>" />
            </a>
        </div>
        <p>
            我要，<a class="blue" href="/customer">注册机荒网</a>，已有帐号，<a class="blue" href="/customer">点这里登录</a>
        </p>
		<?php else:?>
        <div class="login_method">
            <a href="/customer/account/sina?act=authorize">
                <img src="<?php echo $this->getImg('home/zh_sina.jpg')?>" />
            </a>
            <a href="/customer/account/tencent?act=authorize">
                <img src="<?php echo $this->getImg('home/zh_qq.jpg')?>" />
            </a>
        </div>
        <p>
            我要，<a class="blue" href="/customer/account/register?cfrom=index">注册机荒网</a>，已有帐号，<a class="blue" href="javascript:popOpen('login');">点这里登录</a>
        </p>
		<?php endif?>
    </div>
    <!--加入机荒网end-->
    <!--微博ks-->
    <div class="z_weibo" style="height:270px;overflow:hidden;">
		<iframe width="320" height="315" class="share_self"  frameborder="0" scrolling="no" src="http://widget.weibo.com/weiboshow/index.php?language=&width=320&height=315&fansRow=2&ptype=1&speed=0&skin=1&isTitle=0&noborder=0&isWeibo=0&isFans=1&uid=2785673680&verifier=d7633bec&dpc=1"></iframe>
	</div>
    <!--微博end-->
    <div class="clear"></div>
</div>
