<?php $attributes = $this->loadAttributeList()?>
<?php $types = $this->getAttributeValueType()?>
<ul class="tabs1">
	<li>品牌列表</li>
	<li class="tabs1_c">属性列表</li>
</ul>
<!--筛选框ks-->
<div class="search_div">
	<div class="search_div_item">
		<form action="/monitor/system_tlib/add-attribute" method="get">
			<strong>添加属性：</strong>
			<input type="text" name="label" value="" />
			<select name="type">
				<?php foreach ($types as $key => $value):?>
				<option value="<?php echo $key?>"><?php echo $value?></option>
				<?php endforeach?>
			</select>
			<button type="submit">提交</button>
		</form>
	</div>
	<div class="clear"></div>
</div>
<!--筛选框end-->
<div class="table1" entity="tlib-attribute">
	<table width="990">
		<thead>
			<tr>
				<th width="300">属性名称</th>
				<th width="300">属性值类型</th>
				<th width="200">状态</th>
				<th class="tac" width="200">操作</th>
			</tr>
		</thead>
		<tbody>
			<?php if ($attributes):?>
			<?php foreach ($attributes as $attribute):?>
			<tr entity="<?php echo $attribute['id']?>" type="<?php echo $attribute['type']?>">
				<td><?php echo $attribute['label']?></td>
				<td><?php echo $types[$attribute['type']]?></td>
				<td class="green"><?php echo $attribute['status'] ? '有效' : '冻结'?></td>
				<td class="table_cz tac">
					<?php if ($attribute['status']):?>
					<a href="javascript:void(0);" onclick="itemInActive(this, '<?php echo $attribute['id']?>', 'tlib-attribute');">禁用</a>
					<?php else:?>
					<a href="javascript:void(0);" onclick="itemActive(this, '<?php echo $attribute['id']?>', 'tlib-attribute');">启用</a>
					<?php endif;?>
				</td>
			</tr>
			<?php endforeach?>
			<?php else:?>
			<tr>
				<td colspan="8" style="text-align:center;">暂无相关属性记录</td>
			</tr>
			<?php endif?>
		</tbody>
	</table>
</div>
<script type="text/javascript">
jQuery(document).ready(function(){
	jQuery('.tabs1 li:eq(0)').click(function(){
		window.location.href = '/monitor/system_tlib/brand-list';
	});
});
</script>
