<?php $id = Factory::getRequest()->getParam('id')?>
<?php $mobile = $this->showInfo($id)?>
<title>【<?php echo $mobile['title']?>】-顺德二手手机-顺德手机仓库-机荒网</title>
<meta name="KEYWORDS" content='顺德手机,顺德手机交易,顺德二手手机,<?php echo $mobile['data']['brand']?>,<?php echo $mobile['data']['model']?>,顺德闲置手机,佛山手机交易,佛山二手手机,机荒网' />
<meta name="DESCRIPTION" content='<?php echo $mobile['title']?>,<?php echo $mobile['data']['brand']?>,<?php echo $mobile['data']['model']?>' />
