<div class="tis">
	<p>注：新密码不能和用户名重复，不能使用全数字的密码。</p>
</div>
<form action="#" method="post">
    <table style="margin-top:10px;">
        <tr>
            <th>旧密码：</th>
            <td>
                <input type="password" name="pwd" onblur="checkPwd(this);" />
                <label class="error_tis"></label>
            </td>
        </tr>
        <tr>
            <th>新密码：</th>
            <td>
                <input type="password" name="newpwd" />
                <label class="error_tis"></label>
            </td>
        </tr>
        <tr>
            <th>重复密码：</th>
            <td>
                <input type="password" name="repwd" />
                <label class="error_tis"></label>
            </td>
        </tr>
        <tr>
            <th></th>
            <td>
                <button class="btn_orange" type="button" onclick="newPwd(this);" style="height:26px; line-height:22px; padding:0px 15px; border-radius:4px 14px;">保存修改</button>
            </td>
        </tr>
    </table>
</form>
