<?php $id = Factory::getRequest()->getParam('id', null)?>
<?php $model = $this->getModelName($id)?>
<title><?php echo $model['model'] . '-' . $model['brand']?>最新报价-顺德手机导购-机荒网</title>
<meta name="KEYWORDS" content='<?php echo $model['model'] . ',' . $model['brand']?>,顺德手机导购,顺德手机,顺德手机交易,顺德二手手机,顺德闲置手机,佛山手机交易,佛山二手手机,机荒网' />
<meta name="DESCRIPTION" content='<?php echo $model['model'] . ',' . $model['brand']?>,顺德手机导购' />
